bids-standard/bids-specification

- specification.md
Also updating a couple of emojis for additional contributions folks have made.
Specifically:
@dorahermes, @Remi-Gau, @Park-Patrick, @emdupre, @choldgraf  & me (@kirstiejane) 
I haven't included many of the contributors because I'm zooming between meetings - but at least this gets the current folks included.
> Add some bids starter kit contributors

- src/99-appendices/05-units.md
There is actually a difference between [`µ`](https://www.compart.com/en/unicode/U+00B5) and [`μ`](https://www.compart.com/en/unicode/U+03BC).
Previously we had the greek Mu sign, but what we really want is the micro sign.
cf. https://twitter.com/stefanappelhoff/status/1055122338080006144
edit: This same error was also true for the omega sign, which should be an ohm sign:
- https://www.compart.com/en/unicode/U+03A9
- https://www.compart.com/en/unicode/U+2126
> [MRG] unicode: replace greek mu and omega by micro and ohm signs

- src/02-common-principles.md
It is often useful to look at the top level `task*.json` files to see what is
"common" among all subjects/sessions.  Listing only the fields with common
values is what we also implemented (albeit incorrectly, fix is pending
https://github.com/nipy/heudiconv/pull/279) in ReproIn.
Upon quick search I also found no "good practice" recommendations in the
spec.  It might be arguable either spec should or should not include them.
I think it should since we already RECOMMEND things.  We of cause could
place recommendations into a separate subsection somewhere but then they
would not be linked to the specific topics and thus would not be attended
to. Hence I placed this one right at the section where it is pertinent
This PR is largely an RFC ;-)
> ENH: First(?) good practice recommendation. No excessive overrides in Inheritance principle

- src/CHANGES.md
There are no major changes in this release. It serves two purposes:
- testing the release mechanism (especially RTD component contributed by @choldgraf)
- creating a minor release prior to EEG and iEEG merges
> REL: v.1.1.2

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
When users choose to reconstruct both magnitude and phase images from their EPI sequences, they end up with full 4D phase time series. The "part" keyword is [used in BEP001](https://github.com/bids-standard/bep001/blob/1be21287ec2926f239b241e470cbb4c7ecb3f8aa/main.md#8101-filenames) for situations where there is both a magnitude and a phase image.
An alternative to this might be to place the phase time series in `fmap/` and to label them the same way one would label single-volume phase images (i.e., for Case 2 for field maps in the specification).
> Add "part" keyword for mag/phase BOLD images (based on BEP001).

- src/02-common-principles.md
- src/03-modality-agnostic-files.md
there was no indication about which encoding should be used for TSV files. It was probably meant to mention UTF-8, so I added this.
> [MRG] clarify encoding of README, CHANGES, TSV, and JSON files

- CODEOWNERS
- CONTRIBUTING.md
- DECISION-MAKING.md
Dear all,
After months of consultations and deliberations, I have put together a proposal for how we can make decisions. I really wanted the decision rules to be simple, inclusive, and promote consensus. The rules follow the 'doacracy' philosophy - if you want to do something and no one is against it it is going to happen. I think such an approach is very important considering this is a community project in which everyone volunteers their own time. 
The rules fit very well with existing GitHub mechanisms (used by many other repositories) which will make them easy to implement. Hopefully the administrative burden of following them will be minimal.
There are special roles in the decision making process. Anyone can submit a PR and any Contributor can review it. This removes bottlenecks while …
> Adding formal decision-making rules

- src/02-common-principles.md
> [MRG] clarify decimal sep and numerical notation convention

- src/02-common-principles.md
Even the repository is bids-specification
> RF: use "specification" not "protocol" to refer to BIDS

- src/02-common-principles.md
Partially fixes #154. This fixes the example. However I believe a more “theoretical” discussion is required, explaining that raw data are stored directly under the dataset root folder, the same way source data are stored in subfolder `sourcedata` and derived data in subfolder `derivatives`.
> Fix example misalignment

- CODEOWNERS
- src/99-appendices/01-contributors.md
As suggested by @chrisfilo in #155.
> [MISC] Adding Dimitri Papadopoulos Orfanos to the list of contributors

- src/02-common-principles.md
Change dicom converter recommendation from obsolete [dcm2nii](http://people.cas.sc.edu/rorden/mricron/dcm2nii.html) to modern [dcm2niix](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage).
Fixes #165.
> [FIX] changed reference of `dcm2nii` to `dcm2niix`

- DECISION-MAKING.md
Defining a new role - Maintainer - and their "super powers":
- being able to merge any PR (even without reviews or blocked)
- having to sign off on any new release
I also added a language encouraging authors of papers describing extensions to invite maintainers as coauthors. It's not an enforceable rule, but something that would be nice to follow.
This PR is the minimal way to introduce Maintainers to the organization I can think off. In the future, it might be worth revisiting the idea of triaging PRs.
> [MISC] Introducing Stefan Appelhoff as the first Maintainer

- CODEOWNERS
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/99-appendices/01-contributors.md
closes #184 
The text mentioned that the description of the electrical\_stimulation\_\<label> columns had to be placed on \_electrodes.json, but it should be placed on \_events.json. 
This PR fixes the issue.
> [FIX] change file for definition of electrical stimulation labels from _electrodes.json to _events.json

- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
As discussed in the issue #172, I suggest changing the name BrainVision data format in BrainVision Core file data format in iEEG and EEG specifications.
closes #172
> [FIX] Clarify name of "BrainVision" format

- src/04-modality-specific-files/04-intracranial-electroencephalography.md
I removed the `space-<xxx>` from the filename in the section headings, it is still part of the actual specification. 
This should make the following headings and table of contents more similar
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html
> [FIX] make section headings and ToC consistent between meg and eeg specs

- src/99-appendices/06-meg-file-formats.md
before the document migration, we were wrapping up discussion on removing the father-level of folders for all MEG formats except for BTi/4D. The premise of the father-level directory was to compensate for the fact that BTi data is written without file extension. Its data files are generated with the assumption that they all belong to the same folder. 
we proposed adding an additional folder level for this data format. it was extended to a few other file formats but we have realized that this is unnecessary breaks the general pattern. we then proposed to remove the father-level for the file types affected by the superfluous folder level with the exception of BTi where the folder isn't superfluous but necessary.
> [FIX] Remove father-level for meg filetypes other than BTi/4D data

- src/04-modality-specific-files/02-magnetoencephalography.md
The headings for photo, headshape and empty-room were one level lower (i.e. `###` rather than `##`) than they should be.
This should make the following headings and table of contents more similar
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html
- https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html
> [FIX] make MEG section headings and ToC consistent to the EEG and iEEG specs

- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- removed space-<label> from the heading (not from the specification, just the ToC)
- reformatted the chantype table for consistency
- some other minor textual updates
> [FIX] make iEEG ToC more consistent with MEG and EEG

- Pipfile
- Pipfile.lock
closes #208 
This PR is a 2nd attempt to solve the vulnerability issue arising from Jinja2 versions below 2.10.1. Specifically, I am trying to update the Pipfile.lock through `pipenv` instead of manual edits.
This was my workflow:
1. `cd bids-specification`
1. `pip install pipenv` ... can be done in any of your environments
1. `pipenv install` to make an environment for our repository
1. `pipenv shell` to activate the env
1. *do whatever upgrading you want* ... e.g., `pip install -U Jinja2` (upgrade Jinja2)
1. `pipenv lock` to lock the current package versions in the `Pipfile.lock` file
1. git add and commit the changed `Pipfile.lock` and push
Note that I also updated our mkdocs-material version and this lead to upgrades in a lot of our packages.
I have no clue, why the "Markers" …
> [INFRA] bump up mkdocs-materials version

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
While @robertoostenveld and I went over #173, we noticed several minor inaccuracies with the entities that recording modalities can have.
This PR mainly targets a consistent and sensible use of the acq parameter, as also discussed in https://github.com/bids-standard/bids-specification/issues/194#issuecomment-480480719
Furthermore, one superfluous task label is deleted from EEG electrodes.
In Robert's words:
> My confusion is only with task for headshape/photo/electrodes. Those are measurements which are task-independent. See https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv which includes task as required. I think that is incorrect. Electrode data is not recorded while the subject performs a …
> [FIX] Clarify use of acq and task parameters in EEG, MEG, and iEEG

- mkdocs.yml
There is no convenient way to obtain a permalink to reference a specific (sub)section
in the page ATM.  Only top level section urls available in the TOC. With this permalink
those IDs, which are already in HTML anyways, become exposed so it is easy to get
permalink for any section.  I chose # symbol since that is what is used in the URL to
separate out the fragment to point to that ID in the page, e.g.
> [INFRA] Enable permalink urls to appear at (sub)section headings

- src/05-derivatives/01-introduction.md
note that `<value>` is not used anywhere else in the specification
> [FIX] use <label> for _desc- - not some <value> + clarify <value>

- DECISION-MAKING.md
As @franklin-feingold has detected, several of the recently merged PRs to bids-specification have not triggered our automatic changelog generator. This is because the current code for that changelog generator (see [circle.yml file](https://github.com/bids-standard/bids-specification/blob/c782b7a1138cfb2ad9be2f9cfde0e6195e20e0e2/.circleci/config.yml#L29)) only picks up merge commits as a merge method (not rebase, not squash).
In this PR I thus add to the DECISION MAKING, that merges should always be made through the "make a merge commit" method.
This PR is accompanied with some changes to the GitHub repository, where I changed the settings to **only** allow merge commits as the method for merging (see image):
An alternative could be to improve the changelog generator script to also pick up …
> [INFRA] Add clarification on merge methods to DECISION_MAKING

- src/02-common-principles.md
Just matching the filename in the description to that present in the filesystem example.
> [FIX] Common principles: Fix filename in inheritance principle

- CONTRIBUTING.md
- README.md
For consideration to update text in the README and CONTRIBUTING documents.
Related to #273, #275.
Pinging @franklin-feingold @sappelhoff @effigies based on previous conversations, but all feedback is welcome !
[Rendered README](https://github.com/bids-standard/bids-specification/blob/enh/contrib-pathways/README.md).
[Rendered CONTRIBUTING](https://github.com/bids-standard/bids-specification/blob/enh/contrib-pathways/CONTRIBUTING.md).
> [ENH] Update contributing guide and README to make discussion forums easy to find

- Release_Guideline.md
addresses https://github.com/bids-standard/bids-specification/issues/257 and converted from [this google doc](https://docs.google.com/document/d/144Dorxn1e_22iRAvWIfmw-Q9KW7Ce7OZ-KyMHKAk_Qg/edit)
This is in the review phase and comment phase. I thought it could perhaps be easier to work and wrap up in this PR.
> [ENH] adding release guidelines

- Release_Guideline.md
- Release_Protocol.md
Added a git clone command. This was found when opening https://github.com/bids-standard/bids-specification/pull/291 . This command was needed to complete the rest of the procedure when starting from a clean directory
> [ENH] Clarify requirements in Release Protocol

- .circleci/artifact_path
- .circleci/config.yml
This PR introduces a quick link to the specification when a PR is made. To enable this, we would have to install this app: https://github.com/larsoner/circleci-artifacts-redirector. It was developed by @larsoner from the MNE team. If people agree, I think it can really help in reviewing PRs here.
> [INFRA] Link to doc builds in CI checks

- .remarkrc
Set the maximum heading length `lint` check to `false`.
> [INFRA] Set the maximum heading length lint check to `false`

- src/02-common-principles.md
> [FIX] Clarify paragraph about custom data types

- pull_request_template.md
- each sentence on a new line
- use abbreviation "PR" instead of pull request, after first mention
- add new bullet point at the end with some details on how to check out previews etc.
closes #326
> [MISC] add information about continuous integration checks to PR template

- src/03-modality-agnostic-files.md
closes #280 
- make "phenotype" data its own section instead of a subsection of "participants"
- clarify WHERE to place the file, and how to name them
- be more consistent with using MUST, SHOULD, ...
> [ENH] Clarify phenotypic and assessment data in new section

- .github/pull_request_template.md
Move the PR template to a separate folder and use HTML syntax.
The first action helps in reducing clutter in the root folder, and helps
identifying more clearly the GitHub-related files.
The HMTL syntax transition using HTML comments allows the PR template
text not to be part of PR message, and saves the user the task of
deleting it while being still clearly visible when opening a PR.
Minor syntax enhancements.
> [MISC] Move the PR template to a separate folder and improve contents

- src/04-modality-specific-files/03-electroencephalography.md
Related to issue #321. Closes #321 
Just a small addition to make eeg json side car example a valid one according to the specs.
> [FIX] Add SoftwareFilters to EEG sidecar example

- src/04-modality-specific-files/05-task-events.md
Caught a typo while reading—changes "in contract to" to "in contrast to" in 05-task-events.md.
> [FIX] Typo fix (contract -> contrast) in events documentation

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
closes #344 
following the discussion in #344 this is a proposal to:
- clarify the language (make it RECOMMENDED/SHOULD be present) in EEG and iEEG specs
- make this consistently the same across EEG, MEG, iEEG
I think most of us agree that a more strict "MUST" would be more adequate ... but it would break several existing datasets.
This PR can be merged as a backward-compatible, initial improvement, until we finished discussion on whether we should elevate the SHOULD to a MUST.
> FIX: Clarify channels.tsv is RECOMMENDED consistently across ephys

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/99-appendices/06-meg-file-formats.md
closes #365 
As it seems, there were only few instances of <modality>-BIDS left.
I searched the entire repo for:
- EEG-BIDS, BIDS-EEG
- MEG-BIDS, BIDS-MEG
- iEEG-BIDS, BIDS-iEEG
and corrected those I found to just be BIDS.
> FIX: Refer to BIDS consistently, instead of "<Modality>-BIDS"

- README.md
This is an attempt to make the README of the specification repository a bit cleaner.
- structured according to what a potential visitor might want:
- **using** bids
- **asking questions**
- **contributing** to BIDS
What do you think? What else should be addressed?
> [FIX] divide readme into 3 parts

- mkdocs.yml
- src/99-appendices/01-contributors.md
- src/CHANGES.md
releasing specification version 1.2.2 following our [release protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md)
> REL: v1.2.2

- .circleci/config.yml
I am changing the `header-label [LABEL]` parameter to include a `#` sign, so that hopefully the header of our changelog file will be rendered as an actual header.
see: https://github.com/bids-standard/bids-specification/pull/400#discussion_r372834937
- [list of parameters for the changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples)
> [INFRA] fix heading of auto changelog to be a markdown header

- src/CHANGES.md
follow up to #417. This will turn the changelog heading in CHANGES.md into a proper first level heading.
The benefit is (among consistency), that the changelog becomes searchable on [bids-specification.readthedocs.io/](https://bids-specification.readthedocs.io/), which it currently isn't.
#417 made sure that also in future releases this behavior will be preserved.
> [INFRA] add # before heading in CHANGES

- .circleci/artifact_path
- mkdocs.yml
- src/03-modality-agnostic-files.md
- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/05-longitudinal-and-multi-site-studies.md
- src/99-appendices/03-hed.md
- src/99-appendices/07-meg-systems.md
- src/99-appendices/08-coordinate-systems.md
Work on #400 revealed that there were inconsistencies between the mkdocs navigation titles and the section titles in the markdown files, a difference that becomes more evident when only a rendered PDF is examined and compared to the HTML version.
These changes mainly comprise dropping some terms, removing unneeded hypens and removing abbreviations.  The abbreviations, so removed, then do need to be moved into the first line of the corresponding section.
See also #421 that discusses this issue.
> [FIX] Unify section titles and table-of-contents entries

- .circleci/config.yml
closes #332 
Letting our new @bids-maintenance bot user do the bot work. Relieving Franklin's account from the duty :wink: 
Hopefully the correct account will be attributed and linked in the GitHub user interface.
> [INFRA] use new bids-maintenance GitHub account to take over automatic work

- src/05-derivatives/03-imaging.md
- src/05-derivatives/05-functional-derivatives.md
- src/05-derivatives/06-diffusion-derivatives.md
Hello,
I found very small typos/formatting issues. Also, Gray/Grey names were both present. I used US convention to harmonize this.
Best,
Alexandre
> [FIX] Fix typos and formatting

- src/01-introduction.md
I was searching the spec for `bids-validator` and noticed, that no results were shown.
This minor PR allows people to search for bids-validator and also find a link.
> [ENH] Explicitly mention bids-validator and update link

- .circleci/config.yml
With #431 we gained a PDF version of the spec that CircleCI builds upon each merged PR/commit.
With this PR I want to allow us to use a CircleCI API link that will always resolve to the latest generated PDF version.
It'll look somewhat like this:
[`https://circleci.com/api/v1.1/project/github/bids-standard/bids-specification/1957/artifacts/0/bids-spec.pdf?branch=master`](https://circleci.com/api/v1.1/project/github/bids-standard/bids-specification/1957/artifacts/0/bids-spec.pdf?branch=master)
This link is constructed according to the CircleCI [API](https://circleci.com/docs/api/#download-an-artifact-file) and should work.
Current issues:
- See the `1957` in the link --> I had to find this number manually. With the changes in this PR, the `build_docs_pdf` job will always be executed last, …
> [INFRA] Get latest PDF build from CircleCI artifacts

- .circleci/config.yml
follow up #433, which was apparently not sufficient. :disappointed: 
With this PR we ensure that `build_docs_pdf` runs only when all other jobs have successfully finished AND the current branch is `master`.
@franklin-feingold can we get this in despite your opening of #435 ?
> [INFRA] ensure build_docs_pdf CircleCI job runs last

- src/02-common-principles.md
- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/05-task-events.md
see: https://github.com/bids-standard/bids-starter-kit/pull/130#issuecomment-607085403
> FYI, I recall that for BIDS in JSONs CamelCase is preferred, and in TSV headings snake_case is preferred. Not sure whether this principle is formal and/or documented in a general place, out whether it was just personal communication with @chrisgorgo.
I had the same impression as @robertoostenveld and scanned the spec for any part mentioning that convention that we follow.
I did not find it, so I add it with this PR, RECOMMENDING the use of this convention.
> FIX: Clarify  snake_case+CamelCase in TSV+JSON

- src/04-modality-specific-files/08-genetic-descriptor.md
it currently looks like this:
see: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/08-genetic-descriptor.html
I wonder why the linter did not catch this :shrug:
> [FIX] unordered list formatting in BEP018

- .circleci/config.yml
This PR adds an if statement for running our linkchecker. The linkchecker will fail on release PRs due to our changelog pointing to the future specification version (it does not get generated until after the PR has been merged). We want the linkchecker to complete on release branches so we may grab the pdf artifact and upload onto Zenodo
> [INFRA] Add conditional for link-checking releases

- src/index.md
The new PDF rendering isn't presently referenced within the specification.  The place to reference the PDF version is clearly the 'front matter' page `src/index.md`, but I'm not entirely pleased with my addition, tacking on the sentence...
> The entire specification can also be [downloaded as PDF](https://doi.org/10.5281/zenodo.3686061).
... but I couldn't see a more elegant edit.
This addresses #135.
> [FIX] Add reference to PDF on front page of specification

- Release_Protocol.md
Adding the steps to be followed for uploading stable PDFs to Zenodo.
ticks off one more box of To Dos in #407 :slightly_smiling_face:
> [INFRA] add steps for release protocol (PDF upload)

- src/99-appendices/08-coordinate-systems.md
closes #420 
This change is not backward compatible but can be understood as a bugfix. The discussion is captured in #420.
> [FIX] Remove BESA from list of restricted keywords of EEG coordsystems

- DECISION-MAKING.md
This PR is an update to our DECISION-MAKING document, recognizing the current governance we are following.
I left the general GitHub workflow in the document ... but changed its name from "decision making" to "workflow". **This PR is meant as a first step to improve the current state**.
@effigies @franklin-feingold I added you under the Maintainer Group, I don't know your time commitments, so I left it the same as mine (~5h/week), which is a very rough estimate anyway (some weeks more, some weeks less).
> [FIX] update DECISION-MAKING.md document with new governance

- src/03-modality-agnostic-files.md
first step towards #458 
This PR is intended as a fast intervention to improve the documentation about our `participants.tsv`.
It's my intention that all changes made here merely *clarify* and do not prevent us from taking one of the other actions discussed in #458. Yet, I think it's good to make some immediate small improvements and simultaneously think about and discuss long-term higher impact improvements.
This PR is implementing a mix of the suggestions I made in these comments:
- https://github.com/bids-standard/bids-specification/issues/458#issuecomment-620565914
- https://github.com/bids-standard/bids-specification/issues/458#issuecomment-620662939
In particular, I:
- say that age, sex, handedness are often used and we thus recommend (!) some values for them
- stress that a …
> [FIX] clarify participants tsv+json with examples and recommendations

- .circleci/config.yml
It causes github to spit out "429 too many requests" HTTP error (Closes #474).
With this change we should skip ATM about 200 github URLs and be left
with only about 30. Hopefully that would suffice
> [INFRA] linkchecker - ignore github pull and tree URLs

- DECISION-MAKING.md
This pull request is seeking to enhance our current definition of a Maintainer. Our current definition is derived from our [governance document](https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit#bookmark=id.y2yr6itn36kv) and implemented in our [decision-making document](https://github.com/bids-standard/bids-specification/blob/master/DECISION-MAKING.md). 
We intend to add a ~~`Domain expert`~~ ~~`Purview` (edit 5/12)~~ `Scope` (edit 5/14) identification to a Maintainer. This ~~`Domain expert`~~ ~~`Purview` (edit 5/12)~~ `Scope` (edit 5/14) enhancement enables a Maintainer to specify what part of BIDS they intend to be responsible for maintaining. This addition will provide more clarity on how potential maintainers can specifically contribute to the …
> [MISC] Maintainers - `Scope` responsibility

- src/03-modality-agnostic-files.md
Closes #469. Explicitly allows fractional seconds (i.e., sub-second resolution) in `acq_time` column of Scans file. Fractional seconds are (1) optional, (2) must follow a period, and (3) have no restriction on precision.
> [ENH] Allow fractional seconds in scans file datetimes

- src/05-derivatives/03-imaging.md
This PR does the following:
1) Remove conceptual overlap of binary masks and binary dsegs by standardizing on mask and updating the example to show that a single ROI should be renamed to `mask`. I left it under `dseg` to make the connection plain, as I don't think anything would be gained by moving it to mask (which has an ROI example already). This follows a brief discussion with @Lestropie and @edickie in https://github.com/bids-standard/bids-specification/pull/265#discussion_r432818644/https://github.com/bids-standard/bids-specification/pull/265#discussion_r432874774.
2) I added a preface to segmentations (removing parcellation from the section title) to place a conceptual hierarchy of type (discrete vs probabilistic) and a subordinate consideration of representation (volume vs …
> Clarify mask/dseg/probseg in common derivatives

- src/03-modality-agnostic-files.md
Last-minute addition to #265 (Common Derivatives).
This allows for unambiguous identification of raw or derivatives datasets by parsing a single file. This is needed because any feature of derivatives has the potential to be incorporated back into raw, unless it breaks backwards compatibility. In the extreme, it may only be possible to distinguish the two by determining whether a dataset validates as raw or as derivative.
cc @bids-standard/derivatives
> ENH: Add RECOMMENDED DatasetType key to dataset description

- src/02-common-principles.md
closes #492 where @Lestropie observed that the current language on inheritance is very confusing.  
This small PR simply replaces this (common principles) text
> There is no notion of "unsetting" a key/value pair. For example if there is a JSON file corresponding to particular participant/run defining a key/value and there is a JSON file on the root level of the dataset that does not define this key/value it will not be "unset" for all subjects/runs.
with
> There is no notion of "unsetting" a key/value pair. Once a key/value pair is set in a given level in the dataset, lower down in the hierarchy that key/value pair will always have some assigned value.
> [FIX] Clarify language on unsetting a key/value pair

- mkdocs.yml
- src/99-appendices/01-contributors.md
- src/CHANGES.md
This PR coordinates with releasing [Common Derivatives](https://github.com/bids-standard/bids-specification/pull/265) into BIDS!
Following our [release protocol ](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md) this will be merged in 1 week pending further discussions.
> REL: v1.4.0

- src/02-common-principles.md
- src/03-modality-agnostic-files.md
- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/99-appendices/05-units.md
replaces #151 as proposed by @satra , please see discussion therein!
Here is a summary:
- In BIDS we accept SI units only (...and in very special circumstances, custom units - but they'd need to be documented in JSON files)
- Currently, we have nowhere in the spec clarified how the FORMATTING of the SI units should be done (although some users and developers have **assumed** that the [units appendix](https://bids-specification.readthedocs.io/en/stable/99-appendices/05-units.html) shows the required formatting)
- Thus in practice, users have applied either ASCII formatting (e.g., "u" instead of  "µ") or unicode formatting (µ) ... with the problem being that some unicodes **look** the same, while being different (e.g., µ and μ ... micro vs. mu)
This PR is intended to explicitly state how we …
> [FIX] Recommend SI units formatting to adhere to CMIXF-12

- src/04-modality-specific-files/02-magnetoencephalography.md
this section was unclear, see https://github.com/mne-tools/mne-bids/pull/421#issuecomment-633005511
This PR aims at improving / clarifying the used language and examples.
---
I am wondering, why `noise` as a task name and date as a session label have only "SHOULD", and not "MUST" definitions :thinking: anyone got a clue?
> [FIX] clarify MEG empty-room recording naming conventions

- src/05-derivatives/03-imaging.md
> [Fix] 'segmentation' spelling in 05-derivatives/03-imaging.md

- src/pregh-changes.md
Our complete changelog is `GitHub-Changelog-Generator-Output + Pre-GitHub-Changelog`
In this PR I make formatting adjustments to `Pre-GitHub-Changelog` so that our whole changelog is more consistent. (adding links and release dates, consistent newlines)
I also fix several markdown errors. --> Unfortunately the diff is very unreadable, however, no content was changed.
> [Fix] Add links and release dates to pre GH changelog, fix formatting

- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
closes #476 
@dorahermes @maxvandenboom this PR is primarily intended to clear up that the MEF3 format is not a `.mef` file, but a `.mefd` directory.
Do the proposed changes look good to you?
> [FIX] clarify file formats in EEG, iEEG

- mkdocs.yml
- src/04-modality-specific-files/07-behavioral-experiments.md
Reread the behavioral section in light of #513, and realized it's still written in reference to MRI and not electrophysiological or other recordings that we might end up specifying with an alternative data type directory.
Also tried to apply something like a semantic line-breaking scheme, but it wasn't 100% principled and can probably be improved if it seems important.
> [ENH] Update `beh/` specification to contrast with any neural recordings

- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
Today I needed to save some `*_physio` files for the first time and went through the BIDS specification on that topic in detail.
I think the section is currently quite disorganized and not formatted consistently with other BIDS sections.
I took a pass and performed:
- a major restructuring of the paragraphs to accommodate a better "reading flow" from a user perspective
- wording clarifications
The diff is quite large but **I did not introduce new notions or change old ones** (at least not to the best of my knowledge).
Please let me know if you agree that this PR improves the section ... or/and help me to make it  (even) better.
> [FIX] restructure and clarify *_physio/*_stim section

- src/03-modality-agnostic-files.md
closes #450 
Explicitly say that `scans.json` is allowed and recommended if any arbitrary column beyond `filename` and `acq_time` are included.
As discussed in #450 this seems already to be controlled in the validator (to some extend) and reading the remaining spec, this particular style of handling "arbitrary columns" is not new --> thus, I see this rather as a clarification than an enhancement.
> [FIX] clarify that scans.json is allowed and recommended

- src/01-introduction.md
- src/02-common-principles.md
- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/99-appendices/04-entity-table.md
- src/99-appendices/06-meg-file-formats.md
- src/99-appendices/07-meg-systems.md
- src/99-appendices/08-coordinate-systems.md
This PR replaces all non-breaking spaces with spaces (or deletes them if they were adjacent to a space).
As far as I could tell, none of these non-breaking spaces occurred with purpose, but were rather accidental. (Only purpose I can think of is to avoid a number getting separated from a unit, but they have not been used in this way so far in the BIDS spec.)
I realise it doesn't really matter, but my editor highlights them and, in the spirit of keeping clean and simple ascii markdown, I thought they should go.
(For reference these were found with `grep $'\xc2\xa0' *.md`)
> [FIX] Replace all non-breaking spaces with vanilla spaces

- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
crossref:
- https://github.com/bids-standard/bids-validator/issues/1024
- https://github.com/bids-standard/bids-examples/issues/186
I think my proposed change here is already implicit in the specification.
When a TSV is supplied, a JSON MUST be included as well.
Because in _physio or _stim files, the file headers of the TSV are stripped and are shipped in the sidecar JSON.
So if a TSV is supplied but no JSON, the TSV becomes meaningless, because nobody knows about the columns anymore.
This will also have to be checked in the validator bids-standard/bids-validator#1024
> FIX: clarify that <physio|stim>.json is REQUIRED

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Closes #547.
Reorganizes the MRI modality-specific description such that there is a clear distinction between the rec- and ce- entities, and that the _defacemask suffix is not included as an entity.
> [FIX] Reorganize rec, ce entities, _defacemask

- src/02-common-principles.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/99-appendices/06-meg-file-formats.md
In https://github.com/bids-standard/bids-validator/pull/1019 I wanted to add the validation of the newly introduced "fractional seconds" that we allow for `AcquisitionTime` in `scans.tsv` files.
While discussing that code, we stumbled over potential incongruencies between RFC3339 and the way that standard is implemented in BIDS.
- particularly with regards to the timezone (see https://github.com/bids-standard/bids-validator/pull/1019)
In this PR we may clarify/fix some aspects ... or in the least we'll add a link and fix a typo (see 
de4ab9f )
EDIT: we are now adding optional `Z` syntax to indicate UTC time in accordance with RFC3339
> [ENH] Extend date time information to include optional UTC syntax, warn about FIF requirements

- src/02-common-principles.md
closes #541 
Adding requirement levels for the keys in sidecar JSONs that accompany TSV files.
> [FIX] Clarify requirement levels for TSV metadata fields

- src/04-modality-specific-files/03-electroencephalography.md
See #561 and https://github.com/bids-standard/bids-examples/pull/197#discussion_r469153788
This does not close ... #561 since I think that the ACCEL requires some more thought and discussion with other stakeholders.
> [ENH] added PPG as an accepted channel type for EEG, MEG and iEEG

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
At present, zero is not excluded for run and echo indices.  Is this accidental or intended?
If zero's are excluded, this PR will make this explicit.
If zeros are to be discouraged, then perhaps we should say so?
> [FIX] Clarify indices are nonnegative integers.

- src/schema/entities.yaml
This incorporates the changes in #535 to the definitions for the `echo` and `run` entities to the schema. I should have commented directly on #535 about this, but I didn't think of it until this morning.
> [ENH] Specify echo and run indices are nonnegative integers in schema

- src/99-appendices/06-meg-file-formats.md
This is a proposal on how cross-talk and fine-calibration files can be shared using BIDS.
Both files are necessary to make Neuromag/Elekta/MEGIN data usable, more information can be found in these threads:
1. https://github.com/mne-tools/mne-bids/issues/495 ... including a comprehensive discussion about implementation options
1. https://github.com/bids-standard/bids-examples/issues/56 ... basically pointing out the issue many months ago
The proposed solution would require validator adjustments:
1. `.dat` becomes a valid extension for MEG data ... but ONLY if `acq-crosstalk` is part of the file name
1. not sure if we need any adjustments for `*_acq-finecalibration_meg.fif`
Disclaimer: I never worked with Neuromag/Elekta/MEGIN data
Attention needed:
1. is what I am writing in the text …
> [ENH] Specify how to share cross-talk and fine-calibration for Neuromag/Elekta/MEGIN data

- src/99-appendices/08-coordinate-systems.md
closes #493 
- readers will better understand the spec
- once we clarify the spec unambiguously, we can start to implement a better validation, see https://github.com/bids-standard/bids-validator/issues/945 for reference
see: https://github.com/bids-standard/bids-examples/issues/190
In the EEG AND MEG, sections on coordinate systems, we clearly sate that the `<datatype>CoordinateSystem` fields are supposed to be filled with values from a restricted list provided in [appendix 7](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html#coordinate-systems-applicable-to-meg-eeg-and-ieeg)
[Example from  EEG](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson)
> …
> [FIX] clarify XXXCoord* in the coordinate systems appendix

- src/02-common-principles.md
Closes #582.
- Fix within-doc link.
- Fix section title (derivatives was misspelled).
> [FIX] Fix link in Common principles

- src/02-common-principles.md
Micro PR, making the edit suggested in #589, finishing work started in #535, updating definition of `<index>` to clarify that it is a nonnegative integer.
closes #589
> [FIX] Adjust index definition to be nonnegative integer

- .circleci/config.yml
closes #559 
- bump docker version 17.11.0-ce -> 18.06.0-ce
- bump gh chlog version 1.14.3 -> 1.15.2
- add `--release-branch` param for `master`
- add indentation for bash if/else clause
It seems straight forward enough. If I remember correctly, @franklin-feingold's only problem was to *test* whether this actually works as expected.
I didn't test it, but if we merge this and see that it doesn't work, we can revert the changes. WDYT @effigies ?
> [INFRA] use --release-branch option in github-changelog-generator

- .circleci/config.yml
Due to `--since-tag` issue.
- See: https://github.com/bids-standard/bids-specification/pull/594#issuecomment-688709082
- And investigation here: https://gitter.im/github-changelog-generator/chat?at=5f57456cec534f584fedf00d
This param gets automatically set when using `--base` (which we do), because the "base" file gets parsed for versions.
In our case, the latest version in "base" (pregh-changes.md) happens to be `1.1.1`,
and then `--since-tag` is automatically set to `1.1.1` and that tag
cannot be found in the repository, because we never tagged such a
version in git.
Alternative options next to downgrading github-changelog-generator
are:
- to make a PR against github-changelog-generator and add
an option that allows explicitly setting `--since-tag` to None, or
- tagging the first commit …
> [INFRA] downgrade github-changelog-generator to 1.14.3 due to issue with 1.15.2

- src/06-longitudinal-and-multi-site-studies.md
- src/99-appendices/06-meg-file-formats.md
Based on discussion in https://github.com/bids-standard/bids-validator/pull/1053
Specifically see https://github.com/bids-standard/bids-validator/pull/1053#issuecomment-687735083
This is not a breaking change, because all I am changing has not yet been released.
> [FIX] tighter rules for sharing MEG cross-talk and fine-calibration .fif files

- src/02-common-principles.md
Closes #584.
Closes #586.
Reworded slightly from initial suggestion.
> [ENH] Define "modality" and clarify "data type"

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Closes #617.
This is a minor change that places the different MRI data types (func, anat, fmap, and dwi) at the same level as the section "Common metadata fields".
> [INFRA] Move MRI section headings up a level

- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/99-appendices/08-coordinate-systems.md
fixes a bug revealed by @rwblair in https://github.com/bids-standard/bids-validator/issues/1069#issuecomment-694568524
I remember that we used to have `*CoordinateSystemUnits` in the BEPs, but then decided to go for the shorter `*CoordinateUnits`. Apparently we forgot to carefully adjust the text after this change.
On the good hand, the tables describing the keys are all correct and the validator schemas are also all correct, so I consider this a bugfix, correcting wrong text references.
I am surprised for how long this bug remained undetected. Thanks @rwblair for finding it.
> [FIX] Change wrong text references from *CoordinateSystemUnits to *CoordinateUnits

- src/99-appendices/01-contributors.md
- src/99-appendices/06-meg-file-formats.md
- src/CHANGES.md
In GH-598 we accidentally swapped the extensions for fine-calibration and cross-talk files. This PR corrects this.
x-ref: bids-standard/bids-validator#1079
> [FIX] Accidentally swapped Neuromag/Elekta/MEGIN cross-talk & fine-calibration filename extensions

- src/02-common-principles.md
Closes #580. Although I considered adding something to Appendix 5 (Units), it didn't seem to fit well with the contents of the Appendix, so I've limited this change to a single list item in Common Principles#Units.
- Add an item to the additional rules list in Common Principes#Units describing how arbitrary units/unitless data should be handled.
> [ENH] Describe arbitrary units in Common Principles

- src/02-common-principles.md
closes #564
cc @VisLab I entered your suggestion.
We can now discuss it and then get it merged.
Feedback welcome.
> [FIX] clarify definition of events in common principles

- .github/workflows/no-bad-latin.yml
- tools/no-bad-latin.py
- tools/pull_files.py
- tools/requirements.txt
This relates to the issue #635 .
fixes #635 
TODO
Adapting the code from the Turing way was actually easier than anticipated.
The way this is set up, this should look through the files in the `src` folder ignoring the files with extensions listed in `get_all_files` and look for lines that contain the expressions listed in `read_and_check_files`.
Comments lines are skipped. 
Files added to the `src` folder in a PR are also checked
It will trigger the script : 
- on a push to master 
- on a PR to the master branch and will only check files that were modified in `src`
My python is far from fluent so a cross check would be good. :pray: 
~~Any suggestions on how to smartly test a github action? Should I merge into this onto my own master to give this a go.~~
This seems to be set up directly …
> [INFRA] set up github action to detect latin phrases

- pdf_build_src/build_pdf.sh
individual commits might provide more reasoning for the change(s)
> [INFRA] minor robustness enhancements to pdf build shell script 

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Addresses the use case of DWI sequences that need to be split into several runs because, e.g., the scanner would exceed temperature specifications due to fast gradient-switching.
This PR also refactors the text of DWIs to better accommodate the addition and make DWIs more consistent with the rest of the file.
The approach to solve this is similar to that of #622 for fieldmaps.
References: nipreps/dmriprep#43.
> [ENH] Add "multipart DWI" acquisitions and refactor DWI specifications

- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
Closes: #649 
Fixes the template strings in the modality-specific spec to match that of https://bids-specification.readthedocs.io/en/stable/99-appendices/04-entity-table.html#encephalography-eeg-ieeg-and-meg
> [FIX] Fixing template string on electrodes for eeg and ieeg.

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/99-appendices/06-meg-file-formats.md
closes #638 --> the `*_markers` suffix was only defined in the appendix and occurred quite unexpectedly and randomly.
- `*_markers` seems to only apply to KIT/Yokogawa/Ricoh
- This suffix was previously only defined in the appendix: https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#kityokogawaricoh
If we could turn back time we would probably solve the issue on "how to define KIT marker files" without adding a new suffix entirely for that issue.
I suggest this minor fix (this PR) to at least increase transparency of the "markers" suffix in the spec text.
For future enhancements it'd be cool if we could think of a way to somehow salvage the "markers" suffix in a backwards compatible way and put it to some use beyond KIT/Yokogawa/Ricoh. --> …
> [FIX] add paragraph on MEG specific "markers" suffix in MEG spec

- src/02-common-principles.md
Inspired by realization while discussing now merged https://github.com/bids-standard/bids-specification/pull/619 
See individual commits description for more information.  A satellite issue on harmonization of tsv examples ~~will be filed shortly~~ #644
> [MISC] add brief note that TSV example in the spec may currently use either tab or space characters

- src/99-appendices/09-entities.md
- src/schema/entities.yaml
- tools/bids_schema.py
This stems from https://github.com/mne-tools/mne-bids/issues/449#issuecomment-709893588.
- Add the derivatives entities (`res`, `den`, `label`, and `desc`) to the schema.
- Redefine the `space` entity so it works for EEG/MEG/iEEG and MRI data.
- Generate the updated Entities page.
> [SCHEMA] Add derivatives entities to the schema

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Small update to be consistent with the incoming legend on BEP005.
> [MISC] use RFC 2119 language in legend of the "volume timing" table

- CONTRIBUTING.md
The need for guidelines regarding figures in the specifications was mentioned in a meeting related to BEP005 and was also pointed in the PET BEP.
This is a PR to get some sort of guidelines started.
- Do we want to have specific format recommendations for non-vector graphics? png?
- Maybe some size limits on the images too to avoid having people send us 15 Mo images. :-)
I might be overlooking some aspects with the pdf conversion process too that I don't know too well.
> [DOC] add contributing guidelines to add figures in the specs

- src/schema/entities.yaml
In keeping with #616, updating the keys to "common concepts" for inv, res, den and desc. I did not do mt.
> SCHEMA: Update entity YAML keys

- src/schema/datatypes/anat.yaml
This corrects a problem with the CI identified in #719. In #610 we switched to using the entity names, rather than keys, in the datatype YAML files, while in #714 we changed those names for a couple of entities. As such, the old names are referenced in the datatype YAML files, which causes a conflict with the rendering code.
> FIX: Correct entity names in YAML files

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/schema/entities.yaml
> ENH: Clarify run indexing information for MRI acquisitions

- src/schema/datatypes/anat.yaml
References #721.
- Make the `flip` entity optional for the MP2RAGE suffix.
> FIX: Make flip optional for MP2RAGE

- src/schema/datatypes/anat.yaml
Closes None. Stems from https://github.com/bids-standard/bids-validator/pull/1161#discussion_r572940783 by @effigies.
- Add deprecated `T2star`, `PD`, and `FLASH` suffixes back into the schema.
- Rename suffix groups in `anat.yml` to match the variable names in the validator.
> FIX: Add deprecated anatomical MRI suffixes back into schema

- src/schema/datatypes/dwi.yaml
- src/schema/datatypes/func.yaml
Closes None, but stems (in part) from https://github.com/bids-standard/bids-validator/pull/1125#discussion_r571177984.
- Prohibit combination of `echo` entity and `_events` suffix. The echo entity delineates files _within_ an imaging run, so it shouldn't be used for associated files that apply to the whole run.
- Allow `ce` and `dir` entities with `func/` continuous data (the `_physio` and `_stim` suffixes). These entities distinguish imaging runs, so they are required to link the continuous data to the imaging scan.
- For example, we currently could have `sub-X_task-Y_dir-AP_bold.nii.gz`, `sub-X_task-Y_dir-PA_bold.nii.gz`, and `sub-X_task-Y_physio.tsv.gz`, and there would be no way to know which BOLD scan the physio is associated with.
> FIX: Correct schema irregularities for func datatype

- src/04-modality-specific-files/09-positron-emission-tomography.md
In this PR:
* 5ccd8c0 - RF: Regroup PET metadata more in line with MRI convention
* "Information" seemed under-informative. Most were scanner hardware, many could be moved into radiochemistry, and others I broke out into a new "pharmaceuticals" group.
* Also removed language about body weight
* dc555e5 - ENH: Add body_weight examples
* Replaces concept removed in 5ccd8c0 with explicit examples for how it might be used.
* 63a88dd - ENH: Normalize blood data template
* a73a939 - ENH: Simplify blood preface, remove inheritance principle reference
* Follows up https://github.com/bids-standard/bids-specification/pull/633/files#r573830703
* 1b0dc23 - ENH: Use spaces instead of tabs for JSON example
> Additional suggestions for BEP-009

- src/schema/datatypes/eeg.yaml
- src/schema/datatypes/ieeg.yaml
while opening https://github.com/bids-standard/bids-validator/issues/1198 I noticed some inconsistencies in our schema.
Q&A about the changes in this PR.
- Q: Why adding "space" to EEG coordsystem.json and "acq" to iEEG coordsystem.json?
- A: coordsystem.json contains metadata for electrodes.tsv ... so it must support the same entities as electrodes.tsv
- "space" is used to distinguish files from different "coordinate spaces"
- "acq" is used for something like "coordinates digitized pre or post recording" -> acq-pre, acq-post
- Q: Why allow electrodes.json?
- A: that file explains additional arbitrary columns in electrodes.tsv ... these are not added to coordsystem.json, which has a restricted set of metadata that can/must be specified
- And the remaining change is just for consistency, …
> [FIX] schema for i/eeg coordsys+elecs: sub-ses-acq-space are allowed entities

- src/03-modality-agnostic-files.md
- src/06-longitudinal-and-multi-site-studies.md
Closes: #737 
Question: "In case of single-session studies, this file has one compulsory column participant_id that consists of sub-<label>, followed by a list of optional columns describing participants. "  is in the current spec.
What does that mean? In case of single-session studies? Does that mean in single-session studies, this file is compulsory with participant_id a certain way?
> [MISC] Clarify participant_id in participants.tsv file if it exists

- .github/workflows/yml_lint.yml
- .yamllint.yml
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/schema/entities.yaml
minor clarifications concerning iEEG, MEG, EEG:
- related to bids-standard/bids-validator#743
- closes #667 
1. make it more explicit, that labels for the `_space-<label>` entity MUST come from a restricted list of keywords
1. clarify where this list can be found
1. clarify/explain that EEG channels.tsv and electrodes.tsv do not have to correspond
1. edits to the examples for channels.tsv and electrodes.tsv to make them "talk about the same data" and serve to make the previous point obvious
**NOTE**: Also contains a large discussion on the `space` entity, and its lack of support in "raw BIDS" MRI data (supported only for "derivatives" MRI data currently), and more ...
> [FIX] 1) Clarify appropriate labels for space entity, 2) Clarify channels+electrodes do not have to match

- .circleci/config.yml
- DECISION-MAKING.md
- src/99-appendices/03-hed.md
This took much longer than it should have, but this should fix our CIs. fixes #759 
Over the process, I found two separate issues that should be addressed in follow up PRs, see:
- https://github.com/bids-standard/bids-specification/issues/759#issuecomment-806765523
- https://github.com/bids-standard/bids-specification/issues/759#issuecomment-806880527
> [INFRA] Fix CircleCI workflows

- .circleci/config.yml
- pdf_build_src/pandoc_script.py
closes #765 --> by installing `git` prior to the linkchecker job, ... so that we can properly evaluate the if/else logic
fixes the most crucial part of #766 --> by adding a resource path that allows pandoc to find previously missing image files
> [INFRA] install git in linkchecker job

- src/schema/datatypes/pet.yaml
Closes #768.
- Remove the `acq` entity from `pet` and `blood` files.
> [FIX] Remove acq from PET filenames

- CONTRIBUTING.md
- src/schema/README.md
> [DOC] move schema documentation into the schema folder

- src/04-modality-specific-files/09-positron-emission-tomography.md
We had `IntitutionalDepartmentName` in the spec already, see: https://github.com/bids-standard/bids-specification/blame/cc469341d318cf8842a21488876a02d54e959203/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#L130
so `InstitutionDepartmentName` was probably a typo, as found by @tsalo here: https://github.com/bids-standard/bids-specification/pull/762#discussion_r610300623
> FIX: typo in pet: institution -> institutional

- .circleci/config.yml
- mkdocs.yml
- src/CHANGES.md
Preparation for the 1.6.0 release, which notably includes the PET-BIDS extension.
This marks the start of a 1-week freeze period where only clarifying changes will be considered. For more details, please see https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md#4-open-a-pull-request-against-the-master-branch.
> REL: v1.6.0

- src/99-appendices/08-coordinate-systems.md
closes https://github.com/bids-standard/bids-specification/issues/701
- accompanying validator PR: https://github.com/bids-standard/bids-validator/pull/1268
- relevant issue for the EEGLAB bids tools: https://github.com/sccn/bids-matlab-tools/issues/51
cc @arnodelorme @cll008 please check whether the details are correct
> ENH: add EEGLAB as valid coordinate system for EEG

- src/02-common-principles.md
- src/04-modality-specific-files/05-task-events.md
In JSON files, it's possible to document HED tags, similar to how `Levels` are documented.
Previously, this was only documented in the [HED appendix](https://bids-specification.readthedocs.io/en/stable/99-appendices/03-hed.html#annotating-events-by-categories), see this screenshot:
With this PR, I document this feature in "Common Principles" and provide a link to the HED appendix.
All remaining changes are typos and trailing whitespace fixes (we could add a CI for the latter).
> [MISC] Add info on HED key to common principles

- .gitignore
- pdf_build_src/README.md
- pdf_build_src/build_pdf.sh
- pdf_build_src/header_setup.tex
- pdf_build_src/metadata.yml
- pdf_build_src/pandoc_script.py
closes #659 
This took me way longer than it should have ... there are many challenges with our pdf generation code, but I think I fixed more than I destroyed. Some of the options we were passing previously were never actually passed, and I still need to figure out why.
Anyhow, this is a start:
From my side, this is ready to be merged - but a lot remains to be done in the future.
> [INFRA] In PDF, color every other row in table in light gray fill

- src/03-modality-agnostic-files.md
closes #662 
On top of this I plan to add a feature in bids-validator that warns about "suspiciously small READMEs", as discussed in #662.
- bids-validator progress: https://github.com/bids-standard/bids-validator/issues/1279
> [MISC] add link to guide on how to write a good README

- src/04-modality-specific-files/05-task-events.md
- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
> [MISC] Make MRI-centric language more general in Events

- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
fixes #803 
Add the following keys for physio files (NOT for stim files)
> Add device and acquisition metadata for physio files

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Although this note is true (and the b-vecs should be rotated through the head-motion parameters), it is describing some post-processing step.
The actual implication w.r.t. BIDS of the choice of this format is that, if the scanner generates (or better said, receives and forwards) b-vecs in "world coordinates", then they need to be converted into voxel coordinates before writing into BIDS.
BIDS should describe only how the data & metadata should/could be stored. AFAICT, it should not prescribe how to use them whenever possible.
Comes from https://github.com/mattcieslak/bids-specification/pull/1#discussion_r617477112
> [FIX] Amend note about *b*-vecs on DWI specs

- README.md
- mkdocs.yml
- src/02-common-principles.md
previous PRs adding new datatypes did not update these sections, so I am doing that here.
> [MISC] update available datatypes in specification

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/04-modality-specific-files/09-positron-emission-tomography.md
closes #817 
The EEG and iEEG specs had sentences like "columns X, Y, ... are required" before the table outlining the requirement levels. For the iEEG spec, this was furthermore inconsistent.
I removed these sentences before the tables as duplicate information, thereby also fixing the ieeg inconsistency.
I furthermore added a note to the tables where the order column is mandatory. This was not documented consistently before, and many people probably only found out about this by getting the validator error that is generated by these lines:
https://github.com/bids-standard/bids-validator/blob/c60daacf3dbb4cea5a07d5274947c366cf4c0e3a/bids-validator/validators/tsv/tsv.js#L243-L298
@dorahermes I saw your comment voting for making the column order of ieeg files consistent with those of EEG and …
> [FIX] document required column order MEG, EEG, iEEG, PET, and fix typo iEEG

- src/02-common-principles.md
Add missing closing parenthesis in "Storage of derived datasets" section.
> [FIX]: Add missing closing parenthesis in 02-common-principle.md

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
Closes #830.
- Add the `angio` suffix to the table describing non-parametric anatomical MRI suffixes in the specification.
> [FIX] Add angio suffix to the non-parametric aMRI suffix table

- src/03-modality-agnostic-files.md
- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/04-modality-specific-files/07-behavioral-experiments.md
- src/04-modality-specific-files/09-positron-emission-tomography.md
- src/schema/metadata/InstitutionalDepartmentName.yaml
This PR is to keep in synch with changes on the validator and *explicitly* makes "Institutional department name" available for all modalities: it was included in the EEG and MEG json schema of the validator but not in the specs.
https://github.com/bids-standard/bids-validator/pull/1312
> [ENH] make "Institutional department name" available for all datatypes

- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
closes #821 
As proposed by @Aaronearlerichardson I here make explicit in the spec, that the EDF and BDF formats supported in EEG and iEEG also include EDF+ and BDF+.
Both EDF+ and BDF+ are backward compatible with EDF and BDF tools, the file extensions are the same, and technical, open accessible specifications of the formats are available and linked.
@CPernet and @robertoostenveld were not particularly enthusiastic, but also not against this change.
I personally deem this change more of a clarification and I assume that most of the BIDS `.edf` files that are "around" these days are actually EDF+ files anyhow (just my assumption though, I didn't check).
> [MISC] make explicit that EDF+ (and for EEG: BDF+) are included in iEEG / EEG format requirements

- pdf_build_src/process_markdowns.py
This assignment to 'matches' is unnecessary as it is redefined here before
this value is used.
https://lgtm.com/rules/1800095/
This change is rather obvious. Remaining issues (including false positives?) can be found here:
https://lgtm.com/projects/g/bids-standard/bids-specification/
> [INFRA] LGTM warning: Variable defined multiple times

- .gitattributes
As documented in:
* [gitattributes](https://git-scm.com/docs/gitattributes)
* [Configuring Git to handle line endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings).
Fixes #860.
> [INFRA] Enforce consistent line endings via .gitattributes

- pdf_build_src/process_markdowns.py
The value assigned to local variable 'data' is never used.
> [INFRA] LGTM recommendation: Unused local variable

- src/99-appendices/08-coordinate-systems.md
- src/schema/metadata/_iEEGCoordSys.yaml
Fixes https://github.com/bids-standard/bids-specification/issues/747.
> [ENH, MRG] Add "ScanRAS" as an accepted coordinate frame for ieeg

- .lgtm.yml
- pdf_build_src/process_markdowns.py
Previous commit bb6065a from #853 does not work around the LGTM alert.
We attempt to silence the LGTM alert using an [`lgtm.yml`](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file) file, and use standard Flake8 `noqa` suppression comments to document the issue at hand.
Fixes #864.
Links:
* https://lgtm.com/projects/g/bids-standard/bids-specification/snapshot/56824aa6b869bcbec1fb14c50e3771cfc0358af5/files/pdf_build_src/process_markdowns.py?sort=name&dir=ASC&mode=heatmap#xea83c650d9db5491:1
* https://github.com/github/codeql/issues/6517
> [INFRA] Add .lgtm.yml file for better usage of LGTM CI tool

- src/02-common-principles.md
Closes #857 
An alternative could be to establish a new section, like "Case sensitivity" in the same document, which would allow to generalize the rule to cover the entire file path, and then just refer to it from `<label>`.  But was not sure if it would not just get lost among already a good number of sections there, and where to place it.  Sounds like a foundational aspect to me and should be close on top but "what is not as important" there? ;)
edit 1: is there a term to describe such desired behavior?  it is neither "case sensitive" nor "case insensitive" .  "case collision intolerant"?
> [FIX] Clarify case collision intolerance as a file naming principle

- pdf_build_src/process_markdowns.py
- tools/examplecode/example.py
- tools/no-bad-latin.py
The first commit fixes an actual error.
The second commit is about style. I agree style is a question of taste, on the other hand using the standard style does help later maintenance of the code, by other programmers.
> [INFRA] Several style fixes (Flake8) for Python code in the repo

- src/css/watermark.css
fixes #491 
it's probably (I think) the `nav__title` element's background that needs to be changed --> BUT ONLY when the width of the browser is of a certain width or below, see screenshot from browser console (in Chrome):
I applied red color to `nav__title` but:
1. this results in unwanted coloring on **wide** screens, see screenshot: 
1. this gets **overridden** when the screen is narrow (or the browser window is made narrow), see the "strike-through" CSS from the first screenshot in this thread, ... and then what we want to be red is blue again.
So we somehow need to edit/customize the logic that kicks in for narrow browser windows --> and to have that add the red color.
EDIT: tried that via https://stackoverflow.com/questions/13979443/if-screen-resolution-is-less-than-x-append-css/1397 …
> [INFRA] fix draft rendering css on mobile or when browser window is narrow

- src/02-common-principles.md
- src/03-modality-agnostic-files.md
- src/schema/objects/metadata.yaml
Closes None, but adds fields that we previously missed.
- Add two new metadata fields that are described in the phenotypic data section of the spec.
- Add a metadata table for the MeasurementToolMetadata field.
- Add Derivative to the existing tabular data metadata table.
> [SCHEMA] Add MeasurementToolMetadata and Derivative metadata fields

- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/05-derivatives/03-imaging.md
- src/schema/objects/entities.yaml
- src/schema/rules/entities.yaml
fixes #916 
it had slipped through the cracks
> [ENH] add `hemi` entity to schema

- src/04-modality-specific-files/07-behavioral-experiments.md
Add more info and an example concerning for `beh.tsv` an `beh.json`
Related to this issue in the BIDS validator: 
https://github.com/bids-standard/bids-validator/issues/1364
> [ENH] add details for content of `*_beh.json`

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
- src/04-modality-specific-files/08-genetic-descriptor.md
- src/04-modality-specific-files/09-positron-emission-tomography.md
- src/99-appendices/11-qmri.md
Fixes #842 
Add links to example from the BIDS example repo in the following section:
> [ENH] Add links to example datasets for each modality

- .github/workflows/redirect_circleci_artifacts.yml
Following the recommendation of @larsoner :
https://github.com/bids-standard/bids-specification/issues/941#issuecomment-982035117
Closes #941
> [INFRA] fix "CircleCI redirector" GH-action: remove the 2nd (sanity) check

- src/04-modality-specific-files/02-magnetoencephalography.md
Example headshape files should be HEAD and EEG (not ECG).
> [FIX] Typo: ECG_headshape

- src/04-modality-specific-files/10-microscopy.md
- tools/schemacode/schema.py
- tools/schemacode/utils.py
- Add an optional parameter to `schema.make_filename_template`, `n_dupes_to_combine`, that determines the number of suffixes or extensions that should be combined into `<suffix>` or `<extension>`, respectively, when the filename pattern otherwise matches.
- Refactor `utils.combine_extensions` to only combine extensions of compressed versions (for example, `nii.gz` and `nii` will combine to form `nii[.gz]`, but `ome.tif` and `ome` would not combine).
> Address BEP031 macro requests

- src/schema/objects/suffixes.yaml
> [FIX] description: dwi is specialized T2 weighting, not T2*

- src/99-appendices/03-hed.md
- src/99-appendices/11-qmri.md
Two minor spelling errors spotted in the process of generating Lestropie/bids-specification#1, itself an offshoot of #947 (though the errors are unrelated).
> [FIX] Spelling errors in appendices

- DECISION-MAKING.md
- src/99-appendices/01-contributors.md
- Add Eric Earl to the Maintainers Group in `DECISION-MAKING.md`.
- Add Eric Earl's missing contributions to `01-contributors.md`.
> [MISC] Add Eric Earl as a Maintainer

- mkdocs.yml
- src/index.md
This updates links but doesn't address wording/formatting issues that make it harder to find.
cc @arokem
> [MAINT] Update links to starter kit website

- src/02-common-principles.md
- src/03-modality-agnostic-files.md
- src/04-modality-specific-files/05-task-events.md
- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
- src/05-derivatives/02-common-data-types.md
- src/06-longitudinal-and-multi-site-studies.md
- src/99-appendices/03-hed.md
- src/99-appendices/04-entity-table.md
- src/99-appendices/06-meg-file-formats.md
- src/99-appendices/09-entities.md
- src/CHANGES.md
- src/pregh-changes.md
Text is using both 'file name' and 'filename' pretty much to the equal amount
ATM (see git grep outputs below).  Code uses 'filename', and wikipedia has
https://en.wikipedia.org/wiki/Filename and prefers to use 'filename' in it. So
I decided to harmonize  into  'filename'.
$> git grep  'file name' | grep '\.md' | grep -v MACRO | nl
1	src/02-common-principles.md:1.  **File extension** - a portion of the file name after the left-most
2	src/02-common-principles.md:are compulsory. For example a particular file name format is required when
3	src/02-common-principles.md:saved under a particular file name specified in the standard. This standard
4	src/02-common-principles.md:A file name consists of a chain of *entities*, or key-value pairs, a *suffix* and an
5 …
> [FIX] harmonize 'file name' into 'filename'

- .circleci/config.yml
The problem with our linkchecker failing for weeks is the following:
- Mkdocs inserts an HTML header into each HTML site that it builds.
- That header contains a "canonical" URL
- For us, this canonical URL points to the "stable" website, see also: https://www.mkdocs.org/user-guide/configuration/#site_url
- This can be customized here: https://github.com/bids-standard/bids-specification/blob/4bf68b9d0bc09e61879e9196e2e48e1471e0fa2a/mkdocs.yml#L2
This is how it looks:
```html
<!doctype html>
<html lang="en" class="no-js">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="canonical" href="https://bids-specification.readthedocs.io/en/stable/01-introduction.html">
...
```
Whenever we add a new HTML page to the spec, like the glossary, …
> [INFRA] Fix linkchecker

- src/03-modality-agnostic-files.md
- src/99-appendices/03-hed.md
The HED.md appendix has been rewritten to use the current version of HED.
Please review:
@sappelhoff @dungscout96 @happy5214 @tpatpa @smakeig @dorahermes  @IanCa @arnodelorme @Remi-Gau
> [FIX] Update HED appendix to comply with current HED version

- src/schema/objects/metadata.yaml
Follow-up to #622. We realized that as currently worded, there are unresolvable ambiguities for pepolar schemes. Consider the case where you have two BOLD series and one reverse-PE EPI fieldmap. The inputs to estimate the fieldmap could be one or both BOLD files (along with the reverse-PE EPI), and the estimated fieldmap could then apply to one or both.
This allows files to be listed as part of multiple identifiers, and for a BOLD file to be part of an `B0FieldIdentifier` AND have a `B0FieldSource`.
> ENH: Update B0Field metadata to accommodate single-blip fieldmaps

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
inspired by a brief conversation in https://github.com/bids-standard/bids-validator/issues/1410
This PR does not change anything substantial. Apart from fixing line breaks and spelling / capitalization typos,
the only more "substantial" change is adding to MEG that additional columns MAY be added to `channels.tsv`.
> [MISC] minor wording and consistency improvements for channels.tsv in EEG, MEG, iEEG

- src/99-appendices/04-entity-table.md
Closes None.
- Remove uses of the `auxdatatypes` keyword from macro calls, since we dropped the `auxdatatypes` "category" from the schema back in #609. For some reason the entity table functions were still using this keyword. Fortunately, it didn't have any effect on the actual entity tables, but it could be confusing for folks who look at the code.
> [SCHEMA, FIX] Remove mentions of auxdatatypes

- src/schema/rules/datatypes/anat.yaml
@effigies this is pertaining to: https://github.com/bids-standard/bids-specification/issues/977#issuecomment-1020380516
@sappelhoff The PR text told me to ping you for questions. 
Should I add a `Closes:` line to the commit, will this automatically close the issue once merged?
Closes #977.
> [FIX] Optionally support echo entity for VFA suffix

- src/03-modality-agnostic-files.md
- src/schema/objects/columns.yaml
> [FIX] update definition acq_time for sessions.tsv

- src/schema/objects/columns.yaml
- src/schema/objects/entities.yaml
- src/schema/objects/metadata.yaml
closes #746 
make sure that that examples appear "as they should" be in JSON or TSV files
I am sure I have missed some but this is a never ending battle (and I don't thing we want to automate or CI check this) so I suggest that this should close #746
> [FIX] update highlighting of examples, JSON keys and values, and TSV headers or values in the schema

- src/04-modality-specific-files/10-microscopy.md
Attn was brought up in https://github.com/bids-standard/bids-specification/pull/1006#issuecomment-1034936048
by @TheChymera
I think wikipedia would be the most reliable and informative source on TIFF format.
Attn @bids-standard/bep031
> BF: Use wikipedia for TIFF URL, adobe's page is 404ing now

- src/schema/objects/suffixes.yaml
- src/schema/rules/tabular_metadata.yaml
* Representation of second-level files added.
* Homogenization of modality and non-modality file representation.
* Documenting file identifiers such as README and _sessions as
suffixes..
Co-authored-by: Taylor Salo <tsalo006@fiu.edu>
----
As per https://github.com/bids-standard/bids-specification/pull/987#issuecomment-1027163553
@tsalo @yarikoptic
> [SCHEMA] Tabular metadata rules for both top and second-level tabular files

- src/05-derivatives/03-imaging.md
- src/schema/objects/entities.yaml
- src/schema/rules/entities.yaml
Dear BIDS community,
Following an [old discussion](https://github.com/bids-standard/bids-specification/pull/265#issuecomment-558613584) initiated in PR #265, I am opening this PR which introduces the entity `atlas-<label>` for derivatives data, which seems to be necessary to differentiate a different parcellation atlas used for similar type of derivatives data such as segmentation and connectome files (See discussion around it in the [BEP017: Generic BIDS connectivity data schema](https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit?disco=AAAAJxV_uLo)). 
Please let me know what you think and any suggestions for improvements are welcome!
Best,
Sebastien
> [ENH] Introduce the atlas entity for derivatives data

- src/schema/rules/sidecars.yml
This is a duplicate of #1002 into a new branch, for the sake of consolidating the metadata tables before merging into master.
> SCHEMA: Encode first two MR metadata tables as "sidecars.yml"

- src/schema/rules/sidecars.yml
References #1014 and #1002.
- Add YAML definitions for the remaining tables in the MRI page's common metadata fields and anatomy imaging data sections.
> [SCHEMA] Define YAML tables for MRI common metadata fields and anatomy data

- tools/schemacode/schemacode/tests/test_render.py
As discussed in last week's meeting.
Turns out this is a bit more tricky than I thought, because the outputs are large blocks of text which are hard to test w/o reproducing the code that created them or hard-coding output (which will automatically “break” whenever the schema is meaningfully changed — so of limited use, really, and a bit of a chore to re-write for schema contributors).
I tried to hard-code only small stable bits, and come up with some sanity/consistency checks.
Better than nothing, and it will definitely fail if the functions are *badly* broken, but really doesn't cover all the possible failures of the functions...
Another approach would be to assert line number or checksums — that would be less of a chore to update, but still of limited use since they would need to be …
> [SCHEMA] Tests for render listings

- .circleci/config.yml
- CONTRIBUTING.md
- requirements.txt
closes #1030
This is changing the order of instructions:
- first clone
- then navigate to the spec
- then install python via requirements.txt
that's important because we have the schema package, which is local -- so navigating to the local dir of the spec ensures success.
Furthermore I recommend using an isolated python environment -- that way we can do without the "special instructions" in case somebody doesn't want numpy (in an isolated env it doesn't really matter if they have numpy or not).
> [MISC] Rewrite and update html build instructions

- src/schema/objects/formats.yaml
- tools/schemacode/schemacode/tests/test_schema.py
Closes None, but is relevant for #1023.
- Add a `file_relative` format to `schema/objects/formats.yaml`.
- Add tests for the new format.
> [SCHEMA] Add a new `file_relative` format

- src/schema/objects/entities.yaml
As we have now other modalities, such as EEG and MEG, "scan" is not really the
most appropriate term here.  Having said that we do use _scans etc for EEG and
MEG as well ATM, as it was the "forward compatible" with existing MRI-centric
BIDS back then.
> [FIX] run entity - "scans" -> "data samples"

- src/schema/rules/sidecars/fmap.yaml
- src/schema/rules/sidecars/func.yaml
- src/schema/rules/sidecars/meg.yaml
Related to #1014.
Metadata tables for the task fMRI, MEG, and fmap sections.
> [SCHEMA] Add MEG, func, and fmap metadata tables

- src/04-modality-specific-files/09-positron-emission-tomography.md
To make it consistent with the [rules](https://github.com/bids-standard/bids-specification/blob/e47283a268f20b98d5c05ad1bb8c63da3d2a1ceb/src/schema/rules/datatypes/pet.yaml#L30) and the [examples](https://github.com/bids-standard/bids-examples/tree/master/pet003/sub-01/ses-01/pet)
> [FIX] Change recording entity to REQUIRED for pet/blood modality

- src/schema/rules/datatypes/anat.yaml
- src/schema/rules/datatypes/beh.yaml
- src/schema/rules/datatypes/dwi.yaml
- src/schema/rules/datatypes/eeg.yaml
- src/schema/rules/datatypes/fmap.yaml
- src/schema/rules/datatypes/func.yaml
- src/schema/rules/datatypes/ieeg.yaml
- src/schema/rules/datatypes/meg.yaml
- src/schema/rules/datatypes/micr.yaml
- src/schema/rules/datatypes/perf.yaml
- src/schema/rules/datatypes/pet.yaml
- tools/schemacode/schemacode/render.py
This allows us to have an unambiguous name for each rule, such as `schema.rules.datatypes.anat.nonparametric`.
> SCHEMA: Convert datatype lists to objects

- src/schema/rules/datatypes/eeg.yaml
- src/schema/rules/datatypes/ieeg.yaml
- src/schema/rules/datatypes/meg.yaml
Discovered while working on https://github.com/bids-standard/bids-specification/issues/1047
I guess it could be argued against but I feel that such unification makes sense.  There might be other common suffixes where we might want to introduce similar unification.
> ENH: allow for .png and .tif in eeg/ieeg/meg as allowed for micr

- src/schema/rules/sidecars/asl_validation.yaml
- src/schema/rules/sidecars/dwi_validation.yaml
- src/schema/rules/sidecars/eeg.yaml
- src/schema/rules/sidecars/events_validation.yaml
- src/schema/rules/sidecars/fmap_validation.yaml
This PR tackles validation rules for the following error codes:
- 25
- 29
- 30
- 31
- 32
- 33
- 91
- 92
- 157
- 165
- 168
- 172
- 173
- 174
- 175
- 177
- 180
- 181
- 196
- 198
- 199
- 202
> Start drafting validation rules for ASL data

- src/schema/rules/sidecars/asl.yaml
- src/schema/rules/sidecars/asl_validation.yaml
- src/schema/rules/sidecars/beh.yaml
- src/schema/rules/sidecars/continuous.yaml
- src/schema/rules/sidecars/dwi.yaml
- src/schema/rules/sidecars/eeg.yaml
- src/schema/rules/sidecars/entities.yaml
- src/schema/rules/sidecars/events_validation.yaml
- src/schema/rules/sidecars/fmap.yaml
- src/schema/rules/sidecars/fmap_validation.yaml
- src/schema/rules/sidecars/func.yaml
- src/schema/rules/sidecars/ieeg.yaml
- src/schema/rules/sidecars/meg.yaml
- src/schema/rules/sidecars/micr.yaml
- src/schema/rules/sidecars/mri.yaml
- src/schema/rules/sidecars/pet.yaml
- src/schema/rules/tabular_data/eeg.yaml
- src/schema/rules/tabular_data/ieeg.yaml
- src/schema/rules/tabular_data/meg.yaml
- src/schema/rules/tabular_data/pet.yaml
1. Made a lot of edits to lowercase all the OPTIONAL, REQUIRED, RECOMMENDED, PROHIBITED, DEPRECATED, and RECOMMENDED values.
2. Some edits were made to standardize the way issues appeared with "code", "message", and "level" (error or warning) nested under "issue" instead of "name" and "description" un-nested.
> [SCHEMA] Conform the schema/rules files consistently

- src/schema/rules/dataset_metadata.yaml
Two open questions I see:
1) How do we want to encode, e.g. NO_AUTHORS, where we effectively promote dataset_description.Authors from OPTIONAL to REQUIRED?
2) Do we want to specify nested fields, such as `Genetics.Database` directly? Or have some way of specifying a nested structure as its own object?
> [RTM] SCHEMA: Encode requirement levels for dataset_description and genetic_info

- tools/no-bad-latin.py
I had to spend some time to figure out why running that script did nothing for me
but failed in CI for the PR.  Apparently it was because I had to run it while
in tools/ directory.  IMHO it is suboptimal.
With a short message on how many files were analyzed user at least could
get a hint in case if no files were read at all
> ENH: use __file__ instead of getcwd to determine HERE, provide informative message on # of files

- src/schema/rules/checks/asl.yaml
- src/schema/rules/checks/dwi.yaml
- src/schema/rules/checks/events.yaml
- src/schema/rules/checks/fmap.yaml
- src/schema/rules/checks/func.yaml
- src/schema/rules/common_derivatives_validation.yaml
- src/schema/rules/dataset_metadata.yaml
- src/schema/rules/sidecars/anat.yaml
- src/schema/rules/sidecars/asl.yaml
- src/schema/rules/sidecars/beh.yaml
- src/schema/rules/sidecars/continuous.yaml
- src/schema/rules/sidecars/derivatives/common_derivatives.yaml
- src/schema/rules/sidecars/eeg.yaml
- src/schema/rules/sidecars/entities.yaml
- src/schema/rules/sidecars/fmap.yaml
- src/schema/rules/sidecars/func.yaml
- src/schema/rules/sidecars/ieeg.yaml
- src/schema/rules/sidecars/meg.yaml
- src/schema/rules/sidecars/micr.yaml
- src/schema/rules/sidecars/mri.yaml
- src/schema/rules/tabular_data/derivatives/common_derivatives.yaml
- src/schema/rules/tabular_data/pet.yaml
- src/schema/rules/tabular_data/task.yaml
As an intermediary expression language the validator will be attempting to interpret schema rules as javascript where applicable.
Originally the spec used the  `<object> contains "<key-string>"` pattern to avoid the double quotes around the string representing the key from appearing at the start of the line. To get around this issue in this PR the entire line is wrapped in single quotes.
~~Other wonky thing is testing if something is an Array. Current way of evaluating strings as JS may not give us access to the `Array`  class, so its methods are accessed through the `constructor` field of the thing to be tested.~~
Converted all calls of `isArray` and `typeof` to `type(...)` which we will implement as a function in JS space to return 'object', 'array' 'string' etc.
> SCHEMA convert selectors and checks to javascript

- macros_doc.md
- pdf_build_src/process_markdowns.py
- src/schema/objects/columns.yaml
- src/schema/objects/metadata.yaml
- src/schema/objects/suffixes.yaml
- tools/mkdocs_macros_bids/macros.py
- tools/schemacode/schemacode/render.py
To avoid some boilerplate, I wanted to see if we could get away with fixing linking without modifying the macro calls at all, from the spec side.
Patch on top of #1056. Might just be a bad idea, but I want to see if it builds.
- closes #1056 
- closes #974 
- closes #1034
- closes #1011
- closes #1095
> [INFRA] Fix internal links implicitly

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
- src/schema/rules/datatypes/dwi.yaml
Pull request to fix issue #1089 this adds _rec-label to dwi.yaml template to match other MRI image modalities. 
Also related to comment #105
> [ENH] adding optional _rec-label to DWI

- src/99-appendices/08-coordinate-systems.md
Fixes https://github.com/bids-standard/bids-specification/issues/1025 (most basic part).
> [FIX] Clarify that BIDS standard template data is to be in scanner coordinates (MEG, iEEG, EEG)

- src/schema/rules/tabular_metadata.yaml
https://github.com/bids-standard/bids-specification/commit/f04b47ff makes a number of things much more interesting, but if we're doing this, probably best done everywhere.
@effigies
> [FIX] Standardized tabular_metadata.yaml syntax to conform to: f04b47ff

- src/01-introduction.md
This PR adds the Microscopy-BIDS paper citation to the spec.
(https://doi.org/10.3389/fnins.2022.871228)
> [ENH] Add Microscopy-BIDS citation

- .github/workflows/typescript_build.yml
- src/schema/meta/context.yaml
- tools/typescript/.gitignore
- tools/typescript/README.md
- tools/typescript/build-schema-types.ts
- tools/typescript/generate.test.ts
- tools/typescript/generate.ts
This adds a TypeScript build script for the schema context type and some scaffolding to generate types for the rest of the schema to be used by the JavaScript validator. The plan is to automate this and publish the output as an ECMAScript module but for now this just adds the script for manual testing with the validator.
One minor change to the context schema was needed to make this work, typing xyzt_units as a custom object definition.
> [SCHEMA] Generate schema context object TypeScript definitions

- .yamllint.yml
- src/schema/rules/checks/func.yaml
- src/schema/rules/tabular_metadata.yaml
Was
```
$> yamllint -c .yamllint.yml src/schema/                                                   
src/schema/rules/tabular_metadata.yaml
10:23     error    too few spaces before comment  (comments)
11:11     error    too few spaces before comment  (comments)
src/schema/rules/checks/func.yaml
1:1       warning  missing document start "---"  (document-start)
```
inspired by https://github.com/bids-standard/bids-specification/pull/1106/files#r883077519
> [ENH] Ensure consistent indentation for comments in yaml files, address yamllint warning

- src/schema/objects/columns.yaml
Nowhere else do we refer to a column as `[column_name]`, I think. So let's fix that here as well.
> [FIX] fix style of a column reference

- src/schema/rules/tabular_data/meg.yaml
Small change I found while preparing the fNIRS BEP
> [FIX] Fix MEG datatype for tabular data

- src/04-modality-specific-files/10-microscopy.md
- src/schema/objects/extensions.yaml
- src/schema/rules/datatypes/micr.yaml
- tools/schemacode/schemacode/tests/test_validator.py
- tools/schemacode/schemacode/validator.py
Co-authored-by: Satrajit Ghosh <satrajit.ghosh@gmail.com>
- Supersedes: https://github.com/bids-standard/bids-specification/pull/1103
- Example data: https://github.com/bids-standard/bids-examples/pull/315
- Validator: https://github.com/bids-standard/bids-validator/pull/1467
> [ENH] NGFF format support

- src/02-common-principles.md
- src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
closes #1105
Technically, one could argue that this is a backward incompatible change, because we never explicitly said that blank or duplicated headers in TSV files are forbidden.
However, invoking common sense™, I think this would be a fair change.
> [FIX] clarify no blank and duplicated headers in TSV

- .github/workflows/schemacode_ci.yml
renaming happened in f84cd8514 but coverage submission was not adjusted.
That is what resulted (I guess) in no coverage being submitted as in
https://github.com/bids-standard/bids-specification/pull/1120
==> GitHub Actions detected.
Env vars used:
-> GITHUB_ACTIONS:    true
-> GITHUB_HEAD_REF:   validator_inheritance
-> GITHUB_REF:        refs/pull/1120/merge
-> GITHUB_REPOSITORY: bids-standard/bids-specification
-> GITHUB_RUN_ID:     2680833203
-> GITHUB_SHA:        b39dbd75f515e1f2f114437f423cdcaef915c535
-> GITHUB_WORKFLOW:   schemacode_ci
project root: .
Yaml not found, that's ok! Learn more athttp://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy exists disable via -X coveragepy
-> Running coverage xml
No data to report.
==> …
> [FIX] cover bidsschematools not old name schemacode

- src/CHANGES.md
- tools/schemacode/bidsschematools/tests/test_validator.py
- tools/schemacode/bidsschematools/validator.py
Formerly, the validator would index child datasets (i.e. derivatives) automatically when pointed at a parent dataset, and complain about having found more than one `README`, `dataset_description.json`, etc.
> [ENH] Filtering child datasets from parent validation

- src/04-modality-specific-files/02-magnetoencephalography.md
@mcvinding noted to me that the recommendation for empty-room MEG recordings was confusing, as it confounds two practices. 
Some labs record an empty-room recording every morning to be shared, that is then to be used for all subjects/sessions recorded during that day.
Other labs record an empty-room recording prior to each experimental session, those are not shared.
The text specified that it is "RECOMMENDED to perform an empty-room recording for each experimental session" (i.e., non -shared) and subsequently it explained how to organize the daily shared empty-room recordings in a `sub-emptyroom/ses-YYYYMMDD` structure.
The updated text splits the two and does not prescribe the recommended `ses-YYYYMMDD` practice for empty-room recordings done prior to each experimental session, as those …
> [FIX] Clarify MEG empty-room recommendations

- src/schema/rules/top_level_files.yaml
Current wording at
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#changes
Version history of the dataset (describing changes, updates and corrections) MAY
be provided in the form of a `CHANGES` text file. This file MUST follow the
[CPAN Changelog convention](https://metacpan.org/pod/release/HAARG/CPAN-Changes-0.400002/lib/CPAN/Changes/Spec.pod).
The `CHANGES` file MUST be either in ASCII or UTF-8 encoding.
so it MAY be provided, not MUST.  Alerted to by @satra in
https://github.com/dandi/dandi-cli/issues/1055#issuecomment-1189007674
Closes #1127.
> [SCHEMA] Mark CHANGES as optional

- src/04-modality-specific-files/05-task-events.md
- src/schema/objects/columns.yaml
closes #1043 
Adds two minor tweaks to our documentation of `events.tsv`:
1. Don't Use `sample` when the sampling frequency in the raw data is ambiguous / mixed
2. Use a reasonable precision for numeric metadata (onset, duration, response_time, ...)
> [FIX] Discourage use of "sample" in events if sampling frequency is ambiguous, add guidelines for precision

- tools/schemacode/bidsschematools/tests/conftest.py
- tools/schemacode/bidsschematools/tests/test_validator.py
We should also test whether the validation fails when it should fail. This PR does that, leveraging https://github.com/bids-standard/bids-error-examples
> [INFRA] Added error tests

- tools/schemacode/bidsschematools/tests/data/expected_bids_validator_xs_write.log
- tools/schemacode/bidsschematools/tests/test_validator.py
- tools/schemacode/bidsschematools/validator.py
Historical left-over, pointed out by @yarikoptic
> [INFRA] Using label string as in contemporary schema

- .circleci/config.yml
closes #1147 
~~Probably need to use: `[no-]pr-wo-labels`, see: https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples~~
EDIT: I tried around a bit to make PRs appear in the changelog via "opt in", but it turned out to be difficult / impossible. **However**, having an "opt out" is very easy via:
1. `--exclude-labels`
1. and the new label [exclude-from-changelog](https://github.com/bids-standard/bids-specification/labels/exclude-from-changelog) that I just generated: [![exclude-from-changelog](https://img.shields.io/badge/-exclude%20from%20changelog-000000.svg)](https://github.com/bids-standard/bids-specification/labels/exclude-from-changelog)
I think this is a solution that we can work with. We merely need to go through the …
> [INFRA] Curate changelog

- .github/dependabot.yml
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DECISION-MAKING.md
- Release_Guideline.md
- Release_Protocol.md
- macros_doc.md
- src/schema/README.md
includes:
- adding a dependabot that will keep our GitHub Action versions up to date
- some typo and spelling consistency fixes
- brief intro to the way the changelog is generated
- updating "DECISION MAKING" slightly so that "squash commits" and "rebase commits" of PRs are also valid methods of merging PRs (but before a release, the last PR MUST be a "merge commit")
- replacing @franklin-feingold's email in the Code of Conduct with the general bids-maintainers GMAIL account, cc @bids-standard/maintainers
- updating the "PR tags" that we use (like [ENH], [FIX], ...) with [SCHEMA], which we use a lot now
- add documentation about internal links from schema files and the `SPEC_ROOT` fix we have introduced recently
- move @franklin-feingold to "past maintainers" in the BIDS maintainers table …
> [MISC] general documentation updates

- tools/schemacode/setup.cfg
Test suite has started failing with:
```
/flake8_isort.py", line 3, in <module>
from isort import SortImports
ImportError: cannot import name 'SortImports' from 'isort' (/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/isort/__init__.py)
```
Error seen in action here:
https://ppb.chymera.eu/62fd78.log
> [FIX] Solves isort ImportError 

- src/schema/objects/metadata.yaml
since `non-`, regex should have `^`
and place 0-9 first for consistency (complimentary to #1162 by @TheChymera )
> [FIX] clarify alphanumeric

- tools/schemacode/schemacode/tests/test_rules.py
References #1037.
- Add a test that checks that all objects referenced in the schema rules are also defined as schema objects.
To do:
> [SCHEMA] Add internal validation test for schema

- tools/schemacode/LICENSE
Apparently this is better than MIT because it tells people to not bundle
the code without proper change descriptions.
> MIT license document

- tools/schemacode/bidsschematools/schema.py
These files may be passed around and have lives outside of readthedocs url. Having basic provenance info may save someone a headache in the future.
> [SCHEMA] add schema and spec version to object dumped by bidsschematools

- tools/schemacode/bidsschematools/tests/test_validator.py
- tools/schemacode/bidsschematools/validator.py
Initially I though it would be a good idea to use system-wide log and temporary data directories, but it causes all sorts of sandboxing issues, and now that I think of it might leak patient data...
> Default logpaths

- .github/dependabot.yml
I suspect we will ignore from the changelog most the dependabot PRs rather than the other way around, so this should do the trick.
> [INFRA] auto ignore dependencies update from change log

- tools/mkdocs_macros_bids/macros.py
- tools/schemacode/bidsschematools/render.py
Closes None, but fixes an error introduced in #1228.
- Use relative paths in links to glossary and entities pages created by `make_filename_template`.
> [FIX] Use SPEC_ROOT/src_path in `make_filename_template`

- .github/workflows/schemacode_ci.yml
Secrets aren't shared with PRs for good reason. Only run PyPI tests on push builds.
> CI: Skip PyPI tests on PR builds

- src/03-modality-agnostic-files.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/schema/objects/extensions.yaml
came up in:
- https://github.com/mne-tools/mne-bids/issues/1033
I am adding a general recommendation that if file formats consist of several files, that file which would also be passed to I/O software should be listed in scans.tsv.
> [FIX] clarify which file to list in scans.tsv for file formats with multiple files

- tools/schemacode/bidsschematools/render.py
- tools/schemacode/setup.cfg
closes https://github.com/bids-standard/bids-specification/issues/1198
replaces #1219
let's see how this one goes
> [ENH] Add filename template legend

- src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
SPM doesn't deal with that case
> [MISC] Clarify: FieldMap PE technique --> no SPM

- tools/schemacode/bidsschematools/render.py
Closes None. Stems from https://github.com/bids-standard/bids-specification/pull/802#discussion_r957695260.
- In cases where metadata fields or columns allow only certain values (i.e., `enum`s) and there are a large number of those valid values (>15), link to the associated glossary entry instead.
> [STY] Link to glossary in tables with many valid values

- src/schema/objects/entities.yaml
Closes None. I was starting to work on #612 and #1194, when I realized that the actual entity definitions could be improved.
My main goal was to make the link between entities and metadata fields clearer.
> [ENH] Standardize and organize entity descriptions

- src/schema/rules/datatypes/meg.yaml
- tools/schemacode/bidsschematools/render.py
In #1112, I noticed that the overrides of entity formats in MEG used `requirement` instead of the `level` we use elsewhere. They also redundantly include `type: string`, as all entities are string-typed.
When working on the rendering fixes, it seemed we were repeating ourselves a bit and one thing led to another. The fundamental changes:
1) Instead of constructing a `paragraph` string bit by bit, we now build entire lines and create a `lines` list that can be joined once at the end.
2) The functionality in `_format_entity()` function was written several times, so that's abstracted.
3) Constructing the filename line is made simpler by collecting the entity stem, set of suffixes and set of extensions, and iterating at the last moment.
> SCHEMA: Refactor filename template rendering, normalize requirement level in entity overrides

- tools/schemacode/setup.cfg
The `bst` command provided by the bidsschematools package requires click in order to run, yet click is not listed as a dependency in `setup.cfg`.  This PR fixes that.
> [SCHEMA] Add click to bidsschematools requirements

- src/schema/objects/top_level_files.yaml
Proposed in #1112 comments. `name` is neither the file path nor a consistently human-readable string (but `display_name` is this). I think we can drop this without consequence.
> SCHEMA: Drop unstandardized name field from objects.top_level_files

- src/schema/README.md
This PR is a significant rewrite of the `src/schema/README.md`. One small change to the structure of the schema is preemptively described here. It is implemented in #1291.
Reviving https://github.com/bids-standard/bids-specification/pull/1079.
> DOC: Update README with proposed schema conventions

- src/schema/rules/checks/hints.yaml
We only want to generate these messages when the check returns false.
> [SCHEMA] Invert logic of bold onset hints

- .github/workflows/schemacode_ci.yml
- tools/schemacode/bidsschematools/schema.py
- tools/schemacode/bidsschematools/tests/test_schema.py
- tools/schemacode/bidsschematools/types/__init__.py
- tools/schemacode/bidsschematools/types/namespace.py
- tools/schemacode/bidsschematools/validator.py
While working on #1288 a few changes to namespace became necessary/convenient. However, since these are bug-fixes and enhancements, not backwards-incompatible changes, I wanted to break these changes out into their own PR, to keep that one focused.
The changes are:
1) Making it a mutable mapping makes chains of references more tractable. e.g. if objB refers to objA and objC refers to objB, updating the reference schema during dereferencing becomes necessary to avoid multiple passes.
2) Adding a `level` keyword to items/keys/values allows you to do something like `schema.objects.keys(level=2)` to get things like `metadata.RepetitionTime` and `columns.participant_id`.
> [SCHEMA] Refactor namespace

- src/schema/README.md
- src/schema/rules/tabular_data/derivatives/common_derivatives.yaml
- src/schema/rules/tabular_data/eeg.yaml
- src/schema/rules/tabular_data/ieeg.yaml
- src/schema/rules/tabular_data/meg.yaml
- src/schema/rules/tabular_data/modality_agnostic.yaml
- tools/schemacode/bidsschematools/render/tables.py
> SCHEMA: Add index_columns metadata, render in tables

- .github/workflows/redirect_circleci_artifacts.yml
following:
- https://github.com/mne-tools/mne-python/pull/11156
@Remi-Gau I think you recently noted that there are so many of the checks for this CI step. Perhaps this is a solution.
> CI: limit circleci redirector check

- src/04-modality-specific-files/02-magnetoencephalography.md
- src/04-modality-specific-files/03-electroencephalography.md
- src/04-modality-specific-files/04-intracranial-electroencephalography.md
- src/04-modality-specific-files/11-near-infrared-spectroscopy.md
I recently wanted to link to examples in the modality specific specs and saw that only for EEG that was possible (because examples are already subheadings there).
Here I make those examples where it "makes sense" subheadings for all ephys+nirs modalities.
> add more subheadings, improve consistency

- .github/workflows/schemacode_ci.yml
this might help to fix the codecov failures that we have observed for some time now ... because when using a token, API rate limits may be different.
Note I added `CODECOV_TOKEN` as a "secret" in the GitHub settings for this repo.
xref:
- https://github.com/codecov/codecov-action/issues/557#issuecomment-1216781115
> [CI] add codecov token

- Release_Protocol.md
the generalized circleci link to the latest artifact does not work anymore due to updates in the circleci API.
this change updates the protocol accordingly.
> [MISC] update release protocol

- Release_Protocol.md
Updates the release protocol for our recent addition of the `exclude-from-changelog` label. This simplifies the release protocol somewhat.
> [MISC] incorporate gh label into protocol

- src/schema/rules/sidecars/derivatives/common_derivatives.yaml
This rule is intended to apply to spatial reference images:
https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html#spatial-references
These are under specified in the specification, so this rule ended up hitting most everything in some derivative datasets.
> [SCHEMA] Remove rule requiring space metadata for every derivative file without space entity.

- src/schema/rules/files/deriv/imaging.yaml
These tsv files aren't listed in the filename templates for segmentations but are specified as allowed here:
https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#common-image-derived-labels
> [SCHEMA] Add tsv to extensions for any file with dseg suffix.

- src/common-principles.md
By removing extraneous metadata, pipelines generating BIDS datasets can avoid making unnecessary changes.
We are motivated to this since we are working on combining BIDS with [datalad](https://www.datalad.org/) in our workflows, and if a pipeline regenerates hundreds of images with no real change, then we rapidly bloat our storage costs and obscures real changes in `git log`. datalad (thanks to its dependency [git-annex](https://git-annex.branchable.com/)) avoids the bandwidth/storage costs of downstream users, since most of our users download once only, or are always downloading fresh HEAD copies to processing nodes, but our internal storage costs are a big factor for us.
This can be implemented with `gzip -n` in most environments, or equally by running …
> [ENH] Recommend gzip header fields be set to empty values

- src/modality-specific-files/near-infrared-spectroscopy.md
- src/schema/rules/files/raw/task.yaml
> [FIX] add missing processing entity for MEG physio files and render physio filename templates for fNIRS

- src/appendices/meg-file-formats.md
- src/modality-specific-files/magnetoencephalography.md
- src/schema/objects/entities.yaml
- src/schema/objects/metadata.yaml
picking uncontroversial fixes from #1310 to improve consistency. Does **not** resolve the question whether to:
1. deprecate items that are *not* `Neuromag/Elekta/MEGIN` OR
2. treat `Neuromag`, `Elekta`, `MEGIN` and ``-separated combinations thereof as synonyms for `Neuromag/Elekta/MEGIN` (and to introduce this for other MEG systems where the name is made up of different manufacturer names)
> [FIX] make references to Neuromag/Elekta/MEGIN consistent

- src/schema/meta/context.yaml
- src/schema/rules/checks/privacy.yaml
Adds a `gzip` property to the context object and a check that timestamp, filename and comment are all null.
> NF: Add GZIP_HEADER_DATA issue, following gh-1349

- src/appendices/file-collections.md
- src/appendices/qmri.md
- src/modality-specific-files/behavioral-experiments.md
- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/magnetoencephalography.md
- src/modality-specific-files/microscopy.md
- src/modality-specific-files/positron-emission-tomography.md
- src/schema/objects/datatypes.yaml
- src/schema/objects/suffixes.yaml
Was suggestsed in one of the files within
https://github.com/bids-standard/bids-specification/pull/1128/files#diff-374b38cbccac62b8efa8e4ab2552cf9be8ba9eff7c45025abfc6da27d461a37b
and is needed to the recent refactoring done in 251f4400ee44ea5555d418dc12c852b5c3ef7aa0 (#883).
> [DATALAD RUNCMD] Replace mentionings of rules/datatypes with rules/files/raw

- src/modality-specific-files/task-events.md
- src/schema/objects/metadata.yaml
Follow up to https://github.com/bids-standard/bids-specification/pull/1369
> BF: sizes were decided to be in meters. Fix examples

- .github/workflows/schema_docs.yaml
- .gitignore
- tools/schemacode/docs/Makefile
- tools/schemacode/docs/bidsschematools.rst
- tools/schemacode/docs/conf.py
- tools/schemacode/docs/index.rst
- tools/schemacode/docs/make.bat
- tools/schemacode/docs/modules.rst
Setup sphinx to generate RTD page for schema-code and push changes to separate repo at `bids-standard/schema-docs` to trigger build on readthedocs page.
Need to follow up w/ creation of a RTD page as current page [schemadocsplaceholder](https://schemadocsplaceholder.readthedocs.io/en/latest/) is under my account  not bids-standard.
> [MISC][SCHEMA] Add schema-code sphinx generated read the docs to CI; pushes to bids-standard/schema-docs

- .github/workflows/schema_docs.yaml
Updates var from `${{ github.sha }}` to $GITHUB_SHA, was crashing as context was runner env, not actions env in CI call.
> [MISC] update var to runner env from actions env syntax

- src/appendices/hed.md
HED repos and docs have been reorganized. 
The main location of the HED schemas and library schemas is now the `hed-schemas` repository.
Copies of the HED standard schema will remain in the `hed-specification` repository for continuity.
Documentation has been consolidated at [https://www.hed-resources.org](https://www.hed-resources.org).
An example was simplified and a few typos also corrected.
> [FIX] Updated links and fixed typos in hed appendix

- src/schema/objects/common_principles.yaml
In `objects`, we use the `name` field for terms that are the name in name-value pairs, such as column headers, entities or metadata fields. We updated `objects.common_principles` to use `display_name` but did not remove the inapplicable `name` field.
> SCHEMA: Remove inconsistent name field from objects.common_principles

- src/modality-specific-files/near-infrared-spectroscopy.md
- src/schema/objects/columns.yaml
- src/schema/rules/checks/nirs.yaml
- src/schema/rules/tabular_data/nirs.yaml
Following the discussion on issue:
- #1393
(closes #1393)
accompanying validator PR:
- https://github.com/bids-standard/bids-validator/pull/1629
> [FIX] Rename `channels.tsv` column: `orientation_component` to `component`

- src/schema/meta/context.yaml
- src/schema/rules/checks/nifti.yaml
Some existing checks assumed that the NIfTI header had been interpreted, and not simply exposed as fields. This adds `shape == dim[1:dim[0] + 1]` and `voxel_sizes == pixdim[1:dim[0] + 1]`, which can range in length from 0 to 7.
This permits us to do things like check `min(shape) > 0`, which would be more inconvenient to do directly on `dim`.
> SCHEMA: Add convenience objects to nifti_header context

- tools/mkdocs_macros_bids/macros.py
- tools/schemacode/bidsschematools/render/tables.py
- tools/schemacode/bidsschematools/render/text.py
- tools/schemacode/bidsschematools/render/utils.py
- tools/schemacode/bidsschematools/schema.py
- tools/schemacode/bidsschematools/types/namespace.py
- tools/schemacode/bidsschematools/validator.py
Adding some more docstrings for the bidsschematools.
> [ENH] Some missing docstrings for bidsschematools

- tools/schemacode/README.md
The equivalent PyPI badge does not work for some reason :(
https://repology.org/badge/version-for-repo/pypi/bidsschematools.svg?header=PyPI
> [MISC] Expanded readme

- src/schema/objects/metadata.yaml
> [FIX] Close backtick in `TaskName` description

- src/schema/rules/tabular_data/pet.yaml
Sidecar entry `MetaboliteAvail` must be true for this rule to apply, not just present.
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html#blood-recording-data
> SCHEMA Update BloodMetabolite tabular data rule to match surrounding rules.

- src/schema/rules/checks/dwi.yaml
schema based valdiator was throwing errors for *_dwi.json sidecars in root of bids-examples/eeg_rest_fmri.
> SCHEMA bvals bvecs should only be listed missing for datafiles

- src/schema/rules/sidecars/dwi.yaml
We lack sufficient selectors to tell when it should really be required:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#multipart-split-dwi-schemes
> SCHEMA Make multipartid optional.

- src/schema/rules/checks/dwi.yaml
- src/schema/rules/checks/func.yaml
TODO: Purge ` in ` infix operator. Didn't have time. Can do it here or in another PR.
Did not replace all `obj != null` with `type(obj) != "null"` (or `==`). While we did decide on dropping `in`, it sounds like just directly checking null might be less problematic than we thought at first.
> SCHEMA: Minor fixes

- src/modality-specific-files/genetic-descriptor.md
- src/schema/objects/metadata.yaml
also clarify that Genetics.Dataset is required if Genetics is supplied.
closes #1395
- old: https://bids-specification.readthedocs.io/en/latest/modality-specific-files/genetic-descriptor.html
- new: https://bids-specification--1442.org.readthedocs.build/en/1442/modality-specific-files/genetic-descriptor.html
> [FIX] Clarify that dataset_description.Genetics object is required for genetics data

- src/common-principles.md
> [ENH] clarify guiding principles for requirement levels

- .codespellrc
- src/common-principles.md
- src/modality-specific-files/motion.md
- tools/schemacode/bidsschematools/validator.py
The problem is described in:
- https://github.com/codespell-project/codespell/issues/2727 
... maybe we will get some answer soon and before merge of this PR ;)
> Temporarily disable custom codespell dictionary + fix a few fresh typos now detected

- src/derivatives/common-data-types.md
- src/derivatives/imaging.md
- src/derivatives/introduction.md
- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/modality-specific-files/magnetoencephalography.md
- src/modality-specific-files/motion.md
- src/modality-specific-files/near-infrared-spectroscopy.md
- src/schema/rules/files/raw/task.yaml
closes #1456 
**NOTE: see update below this post**
Looking at this more closely, I was a bit surprised to see "channels" as a potential suffix in the filename templates for MOTION ... but not for EEG.
This first commit is to try out what works and what doesn't: adding `photo` and `coordsystem` as well (see EEG spec: https://bids-specification.readthedocs.io/en/latest/modality-specific-files/electroencephalography.html)
Maybe we need to discuss this in more depth.
This is how it would look with the present changes: https://bids-specification--1458.org.readthedocs.build/en/1458/modality-specific-files/electroencephalography.html 
... it looks good to me, it picks up all the correct extensions.
cc @Remi-Gau
> [MISC] consistently list filename templates; `ext` --> `extension`; `_photo.jpg` --> `_photo.<extension>`

- src/schema/objects/columns.yaml
- src/schema/rules/tabular_data/task.yaml
closes #1441 
As discussed in this comment:
- https://github.com/bids-standard/bids-specification/pull/1441#issuecomment-1482554152
Cc @Andesha @christinerogers
> [FIX] Demote `sample` and `value` columns in `events.tsv` from OPTIONAL to arbitrary

- tools/schemacode/bidsschematools/validator.py
Ideally we would inform the user that validation was successful. Could also do it with a print call... but logging seems like it would prevent stdout from getting cluttered when this is used as a lib.
Let me know :)
> Logging info on error-less validation, better warning/error separation

- src/appendices/qmri.md
- The documentation of the RB1COR receive sensitivity mapping file collection referred to different "transmit" coils, rather than different "receive" coils. This is fixed by this pull request. Note that because the body coil can typically be used as a receive coil and a transmit coil, I have used the phrasing "coil in receive mode" rather than "receive coil".
-  It was unclear to me whether "upon subsequent scans" referred to the two RB1COR images being acquired sequentially, or to the possibility of acquiring a separate receive sensitivity map for each element of an MPM file collection. I have attempted to clarify this.
> [FIX] Clean up qMRI RB1COR notes

- src/common-principles.md
- src/schema/objects/formats.yaml
In continuation of previous discussions, including https://github.com/bids-standard/bids-specification/pull/535/
A bit of theoretical background:
* An *index* simply labels elements of another set. There's no particular reason for zero to not be an index, in fact it might be the most used one :) 
* The confusion zero sometimes causes is when it is used as an *ordinal*, since it leads to an asymmetric break in the number line by virtue of being its own inverse additive. Notably there is no year 0AD (or BC). Mathematically this can be considered an atavism, 0th is a valid ordinal, the problem with having a year 0 is that it causes asymmetry since distances between years would need to be calculated based on their start/end regardless of their position, and not based on their start if BC and …
> [FIX] Revert index (entity format) definition to be a non-negative number, permitting zero

- .github/workflows/schemacode_ci.yml
Schema 0.7.0 failed to upload because our build process requires being able to import the entire module. We should come up with a better solution, but this is needed for now.
Mostly just want to test PR builds for the bidsschematools RTD.
> CI: Add pyparsing to build requirements

- DECISION-MAKING.md
Just went through git blame to figure out when people joined the maintainers group. Not sure if this is actually useful or desirable, but figured I'd post a patch and see who bites.
The Mar 2020 date corresponds to when we actually made this table, which I consider the formal start of the group.
Added @rwblair in Mar 2020, since he's been maintaining the validator. He was added to the table in August 2022, which is obviously incorrect. I don't remember when he started joining maintenance meetings, or if that was from the start.
If this is not valuable, feel free to close.
> DOC: Add join/leave dates to maintainers tables

- macros_doc.md
- src/modality-agnostic-files.md
- src/modality-specific-files/genetic-descriptor.md
- src/schema/objects/files.yaml
- tools/mkdocs_macros_bids/__init__.py
- tools/mkdocs_macros_bids/macros.py
- tools/mkdocs_macros_bids/main.py
- tools/schemacode/bidsschematools/render/__init__.py
- tools/schemacode/bidsschematools/render/text.py
- tools/schemacode/bidsschematools/tests/test_render_text.py
closes #1038 
- adds a macro to directly render the description of an "object" in the schema
- removes duplicate information from text that was already in schema
- update schema descriptions with info that only existed in the text of the spec
> [ENH] Add macro to render descriptions

- src/schema/rules/sidecars/derivatives/common_derivatives.yaml
The specification says `SkullStripped` is required for [Preprocessed, coregistered and/or resampled volumes](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#preprocessed-coregistered-andor-resampled-volumes), but is not listed for masks or segmentations. It's not clear that it's useful for these derviatives, so I propose removing this rule.
Appears when attempting to validate fMRIPrep derivatives:
```console
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ds000001-fmriprep                                                                                                                 │
└──────────────────────────────────────────────────────────────────────────────────── …
```
> SCHEMA: Relax SkullStripped metadata requirement for masks and segmentations

- .codecov.yml
Based on the recommendations in [[0]], a hard-coded token is the only way to reliably get PRs from forks to submit coverage until rate-limiting on Codecov's use of the GitHub API are resolved. The scope of this token only permits an attacker to upload bad coverage reports, so the threat seems acceptably small.
[0]: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
> CI: Hard-code codecov token so PRs can submit coverage

- src/common-principles.md
related to https://github.com/bids-standard/bids-specification/issues/1487
> [ENH] Clarify that data files must be uniquely identified by entities/suffix

- src/modality-specific-files/physiological-and-other-continuous-recordings.md
> [FIX] Add missing column description in physio example

- tools/schemacode/bidsschematools/data/__init__.py
- tools/schemacode/bidsschematools/tests/data/__init__.py
- tools/schemacode/bidsschematools/tests/test_schema.py
- tools/schemacode/bidsschematools/tests/test_validator.py
- tools/schemacode/bidsschematools/utils.py
- tools/schemacode/docs/conf.py
- tools/schemacode/docs/requirements.txt
While working on documentation, I noticed we have data modules with nothing in them. Been playing around with ideas to make resource fetching more streamlined, and created a `Loader()` class that streamlines loading and shows the available data when its docstring is rendered.
> SCHEMACODE: Add data loader class

- src/appendices/meg-file-formats.md
This `>` sign has been at the end of these filenames since v1.1.2 at least.
> FIX: Trail MEG directory formats with `/`

- src/schema/meta/associations.yaml
One difficulty with validation is knowing when it is worth making the effort to load an associated file. This meta-schema is intended to hint to validators and other implementations when associations may be relevant.
It could make sense to add filename rules here, as well as indicators of whether a file can be found through inheritance (making some path components optional) or not. For example `magnitude` images will never be found through inheritance, but must match all entities with their corresponding `fieldmap` images. `bval` and `bvec`, however, can be inherited.
> SCHEMA: Define associated data with selectors, path components and inheritance

- mkdocs.yml
- src/appendices/schema.md
> [ENH] add schema in appendix

- src/schema/objects/metadata.yaml
fixes #1542
- allows `unkwown` and `none` contrast agent
> [ENH] Allow UNKNOWN and NONE ContrastBolusIngredients

- src/schema/README.md
- src/schema/meta/associations.yaml
Had some `matches()` which isn't valid.
Validator output:
```
DEBUG TypeError: matches is not a function
at eval (eval at evalConstructor (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:36:32), <anonymous>:3:25)
at evalCheck (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:74:12)
at file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:128:34
at Array.every (<anonymous>)
at mapEvalCheck (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:128:21)
at evalRule (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:116:26)
at applyRules (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/applyRules.ts:44:7)
at …
```
> SCHEMA: Fix match() expression function

- src/schema/rules/sidecars/func.yaml
Validation is failing on derivatives datasets because things like `func/*_dseg.nii.gz` are both MRI and in `func/` but they no longer have timing information.
Will add more fixes like this in the next 30 minutes, but after that, merge at will.
> SCHEMA: Fix overeager BOLD rules

- src/schema/rules/tabular_data/pet.yaml
BloodPlasma requirement in tabular data didn't check if the corresponding json was true. All jsons are required to have the PlasmaAvail field, so any dataset with PlasmaAvail false would fail this check.
> [SCHEMA] Update pet.yaml PlasmaAvail check.

- src/schema/rules/tabular_data/nirs.yaml
- relates to https://github.com/bids-standard/bids-examples/issues/396
makes it consistent with what is done in EEG, iEEG, MEG
See the HTML table [here](https://bids-specification--1597.org.readthedocs.build/en/1597/modality-specific-files/near-infrared-spectroscopy.html#channels-description-_channelstsv)
@rob-luke @lpollonini does this make sense to you
Closes bids-standard/bids-examples#396.
> [ENH] Add optional low_cutoff and high_cutoff columns for fnirs channels.tsv

- src/schema/rules/checks/nirs.yaml
Ensures that the check is happening against a value that matches booleans format regex.
> [SCHEMA] Update nirs.yaml ShortChannelCountReq check.

- .pre-commit-config.yaml
- DECISION-MAKING.md
- src/derivatives/imaging.md
- src/schema/objects/entities.yaml
- src/schema/rules/entities.yaml
- src/schema/rules/sidecars/derivatives/common_derivatives.yaml
During the [BIDS derivative meeting](https://openneuropet.github.io/bidsderivativemeeting/) in June, the [atlas BEP0038](https://bids.neuroimaging.io/bep038) was thoroughly discussed. You can see a summary of the discussions [here](https://docs.google.com/document/d/1JtTu5u7XTkWxxnCIH6sxGajGn1qG_syJ-p14aejpk3E/edit).
The outcome of this discussion was that the concept of an atlas is broader than what the [current atlas entity](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#atlas) defines it to be, so we would like to replace the current atlas entity which was basically representing a segmentation of a derived dataset with the entity "seg" instead. Currently, we define what [segmentation](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-ima …
> [SCHEMA][ENH] Remove atlas entity and replace it with seg in prep of BEP038

- src/schema/objects/columns.yaml
While schematizing, the `notch` column was defined as a number. In the case of iEEG at least, the BEP leads had submitted examples where `notch` took the form `[F1, F2, F3]`. This PR recognizes this as existing practice and suggests that curators and tools adopt `[F1, F2, ...]` for interoperability, but does not require it.
cc @bids-standard/raw-electrophys for comment.
Closes https://github.com/bids-standard/bids-examples/issues/395.
> FIX: Do not require notch frequencies to be parsed as numbers, accommodating multiples

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/rules/sidecars/mri.yaml
Closes #1585.
- Create new rule, `SliceTimingMRI`, making `SliceTiming` a recommended field for MRI scans with `MRAcquisitionType` set to `2D`. This way, `SliceTiming` is no longer recommended for 3D acquisitions.
> Recommend SliceTiming if MRAcquisitionType is "2D"

- src/schema/meta/context.yaml
- src/schema/rules/checks/dwi.yaml
- src/schema/rules/errors.yaml
This is an alternative to #1609. Instead of directly referencing bval/bvec shape on these files, we can operate on the associations. Constructing the association should take more time than parsing the file, so this should be a net optimization, even though we will end up processing the rule more times.
> SCHEMA: Update DWI rules to check bval/bvec size in associations

- src/appendices/hed.md
Squashed #1592 without some merge noise that reverted unrelated changes.
@tpatpa @VisLab Can you please review to make sure I didn't lose any of the originally planned changes?
Closes #1592.
> [FIX] Hierarchical Event Descriptors (HED) page update

- src/schema/meta/expression_tests.yaml
We started with a pretty ambitious expression language, thinking it would not be hard to implement in any language. It turns out that it would require a proper parser, which would probably be an intolerable slowdown to the javascript implementation. Making `null` "falsey" is enough, and we don't use much of the fall-through behavior we originally designed.
A Python implementation will be able to do some type-checking on the expressions we actually have to make sure they stay in the bounds the JS implementation can handle.
> SCHEMA: Make expression tests more manageable

- src/schema/rules/sidecars/entity_rules.yaml
Already covered by rules.sidecars.pet.PETRadioChemistry, and avoids hitting this rule for blood files.
Fixes https://github.com/bids-standard/bids-examples/issues/416
> FIX/SCHEMA: Remove TracerName requirement for trc entity

- src/modality-agnostic-files.md
- src/schema/objects/metadata.yaml
What we have
❯ git grep '"Units":'
src/appendices/hed.md:    "Units": "s",
src/appendices/hed.md:       "Units": "ms",
src/appendices/qmri.md:      "Units": "RECOMMENDED",
src/appendices/qmri.md:"Units": "second",
src/common-principles.md:        "Units": "RECOMMENDED",
src/common-principles.md:    "Units": "kg/m^2",
src/modality-agnostic-files.md:        "Units": "years"
src/modality-specific-files/magnetic-resonance-imaging-data.md:   "Units": "rad"
src/modality-specific-files/magnetic-resonance-imaging-data.md:   "Units": "rad/s",
src/modality-specific-files/physiological-and-other-continuous-recordings.md:        "Units": "mV"
src/modality-specific-files/physiological-and-other-continuous-recordings.md:        "Units": "mV"
src/modality-specific-files/positron-emission-tomography.md: …
> Fix years and degrees Units and unit to be singular to match the rest

- .lgtm.yml
LGTM.com has been deprecated and replaced by GitHub code analysis:
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
> [INFRA] Remove LGTM.com configuration file

- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/magnetoencephalography.md
- src/schema/objects/metadata.yaml
- src/schema/rules/sidecars/eeg.yaml
- src/schema/rules/sidecars/meg.yaml
- closes #1635 
related bids-validator legacy PR:
- https://github.com/bids-standard/bids-validator/pull/1831
> [ENH] add `ElectricalStimulation` and `*Parameters` metadata to MEEG jsons

- src/schema/objects/metadata.yaml
Follow-up to #1603. Needed to support levels with schema validator.
xref https://github.com/bids-standard/bids-examples/pull/413
> SCHEMA: Enable structured Level descriptions for TSV columns

- src/schema/meta/context.yaml
- src/schema/objects/columns.yaml
- src/schema/objects/enums.yaml
- src/schema/objects/metadata.yaml
- src/schema/rules/files/raw/meg.yaml
- Addresses part of #1529 
specifically, I intend to add definitions for those "enums" that don't have one yet.
See @tsalo and my discussion here: https://github.com/bids-standard/bids-specification/pull/919#issuecomment-1602963705
```
type: string
enum:
- left
- l
- L
- LEFT
- Left
```
> [SCHEMA] Add remaining enum definitions

- src/derivatives/common-data-types.md
add descriptions.tsv file as optional based on the derivatives guidelines https://docs.google.com/document/d/1JtTu5u7XTkWxxnCIH6sxGajGn1qG_syJ-p14aejpk3E/edit?usp=sharing
> [ENH] Add `descriptions.tsv` file relating to the `desc-<label>` entity

- src/schema/rules/checks/dwi.yaml
- src/schema/rules/checks/nirs.yaml
- src/schema/rules/sidecars/nirs.yaml
Only one schema rule fix for today.
Edit: Okay, a couple more.
> SCHEMA: Fix diffusion and NIRS rules

- src/common-principles.md
- src/modality-specific-files/task-events.md
- src/schema/objects/columns.yaml
- src/schema/objects/metadata.yaml
- src/schema/rules/tabular_data/task.yaml
* See #1446 for extensive discussion.
Closes #1446.
> ENH: Define channel column for events and Delimiter field for column descriptions

- Release_Protocol.md
- related to: https://github.com/bids-standard/bids-website/pull/363
> [MISC] Update release protocol with regards to BIDS BEP Gantt chart (website)

- src/appendices/schema.md
Dead link to the schema folder on this page:
https://bids-specification.readthedocs.io/en/latest/appendices/schema.html
> [FIX] Fix dead link

- src/schema/rules/files/raw/fmap.yaml
> [FIX] Add `part-<value>` to the PEPOLAR fieldmaps

- .pre-commit-config.yaml
- tools/examplecode/__init__.py
- tools/mkdocs_macros_bids/macros.py
- tools/mkdocs_macros_bids/main.py
- tools/pull_files.py
- tools/schemacode/bidsschematools/data/__init__.py
- tools/schemacode/bidsschematools/data/tests/test_rules.py
- tools/schemacode/bidsschematools/expressions.py
- tools/schemacode/bidsschematools/render/__init__.py
- tools/schemacode/bidsschematools/render/tables.py
- tools/schemacode/bidsschematools/render/text.py
- tools/schemacode/bidsschematools/render/utils.py
- tools/schemacode/bidsschematools/rules.py
- tools/schemacode/bidsschematools/schema.py
- tools/schemacode/bidsschematools/tests/data/__init__.py
- tools/schemacode/bidsschematools/tests/test_render_tables.py
- tools/schemacode/bidsschematools/tests/test_render_text.py
- tools/schemacode/bidsschematools/tests/test_schema.py
- tools/schemacode/bidsschematools/types/namespace.py
- tools/schemacode/bidsschematools/utils.py
update precommit hook and apply it
> [STY] apply black 24.1.0

- .circleci/config.yml
- vaguely related to: https://github.com/bids-standard/bids-specification/issues/1695
fixes some minor issues in the circle ci config (use non deprecated images, use yml arrays to pacify schema validation...)
> [MAINT] update circle ci config

- src/schema/rules/files/raw/task.yaml
> [FIX] Remove task entity from DWI and PERF time series file templates

- src/common-principles.md
- src/modality-specific-files/motion.md
The motion spec does not say whether there is a header column or not, only that the columns must match the rows of channels.tsv. From unofficial communications, I believe the intent is that motion.tsv files do not have column headers, and channels.tsv defines the column names.
This changes it to state explicitly that there are no column headers, and that the ordering is defined by the rows in channels.tsv.
cc @sjeung @JuliusWelzel
> ENH: Clarify the relation of motion.tsv columns to channels.tsv rows

- tools/schemacode/bidsschematools/rules.py
The previous implementation assumed that, if a file rule only contained TSV or JSON files, then at least one of these was not inheritable. This seems to contradict the inheritance principle, unless the files cease to be "metadata" files, as well as fails to validate actual files in examples, such as `channels.tsv` and `events.tsv`.
If the rule needs to become more complex, the schema will need a way to indicate whether a rule addresses data or metadata files.
> [SCHEMATOOLS] Implement inheritance for all TSV/JSON files

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/positron-emission-tomography.md
- src/schema/rules/sidecars/mri.yaml
- src/schema/rules/sidecars/pet.yaml
Adds `BodyPart`, `BodyPartDetails` and `BodyPartDetailsOntology` to MRI and PET imaging, taken from additions in BEP 031 - Microscopy. `BodyPart` corresponds to a DICOM tag (0018, 0015 `Body Part Examined`), while the others are for additional annotation when this is insufficient detail.
The more straightforward part of #1396. This complements #1586, which proposes to use the `chunk-<index>` entity to identify different fields of view in MRI, which we expect will most commonly be used for spinal cord imaging.
This also lays some groundwork for BEP22 (MRS), which is waiting on a release with motion before starting their final review process.
> ENH: Add sample metadata to MRI and PET

- src/modality-specific-files/genetic-descriptor.md
Add a missing word to the first line of `genetic-descriptor.md`.
> [FIX] Missing word in `genetic-descriptor.md`

- src/schema/objects/columns.yaml
Should be plural
```
❯ git grep SpatialAxes
src/modality-specific-files/motion.md:| SpatialAxes   | RECOMMENDED                                            | [string][] | The coordinate system in which the motion data are to be interpreted. A sequence of characters from the set `{'A', 'P', 'L', 'R', 'S', 'I', '_'}` indicating the direction of each axis. For example `"ARS"` indicates positive values in the X, Y, Z axes are respectively anterior, right, and superior of the origin, while `"PLI"` indicates positive values are posterior, left, and inferior of the origin. The `"_"` character may be used for unused axes. |
src/modality-specific-files/motion.md:        "SpatialAxes": "ALS",
src/schema/objects/columns.yaml:    `RotationOrder`, and `SpatialAxes`, and MAY use `Description` for the …
```
> [FIX] Typo in reference_frame description (SpatialAxis -> SpatialAxes)

- .gitignore
- .remarkrc
- CONTRIBUTING.md
- mkdocs.yml
- pdf_build_src/pandoc_script.py
- pdf_build_src/process_markdowns.py
- pdf_build_src/remove_admonitions.py
- pdf_build_src/test_remove_admonitions.py
- pdf_build_src/tests/data/expected/README.md
- pdf_build_src/tests/data/expected/modality-specific-files/magnetic-resonance-imaging-data.md
- pdf_build_src/tests/data/input/README.md
- pdf_build_src/tests/data/input/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/genetic-descriptor.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/magnetoencephalography.md
- src/modality-specific-files/microscopy.md
- src/modality-specific-files/motion.md
- src/modality-specific-files/near-infrared-spectroscopy.md
- src/modality-specific-files/physiological-and-other-continuous-recordings.md
- src/modality-specific-files/positron-emission-tomography.md
- add a script to remove mkdoc admonitions 
- run it during pdf build
- add minimal testing to help debugging if needed
- add example admonition to highlight the bids examples repo
> [ENH] allow using of mkdoc admonitions

- tools/schemacode/bidsschematools/data/tests/test_rules.py
Test was written by @TheChymera awhile back.  I didn't check if it was failing at that point but it is all nice and green now:
```
❯ python -m pytest -s -v bidsschematools/data/tests/test_rules.py::test_rule_objects
======================================== test session starts ========================================
platform linux -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0 -- /home/yoh/proj/bids/bids-specification/tools/schemacode/venvs/dev3/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/bids/bids-specification/tools/schemacode
configfile: pyproject.toml
plugins: cov-4.1.0
collected 1 item                                                                                    
bidsschematools/data/tests/test_rules.py::test_rule_objects PASSED
```
on master (does fail on #1705)
> [SCHEMA] Remove stale test comment -- test no longer fails!

- src/common-principles.md
- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/modality-specific-files/microscopy.md
- src/modality-specific-files/motion.md
- src/modality-specific-files/near-infrared-spectroscopy.md
> [FIX] Remove mentions of sourcedata in the datatype specific pages

- src/schema/objects/formats.yaml
Discovered thanks to @ericearl's magical database. Some people generated TSVs that space-pad their numerical columns. Actual tools don't have a problem interpreting these numbers (pandas, deno, Python), just our regular expressions that we use to validate the columns as strings.
> SCHEMA: Allow surrounding whitespace in integers

- src/common-principles.md
- src/modality-specific-files/physiological-and-other-continuous-recordings.md
Their description is hedged within the physiological recordings so upcasting them to the common principles seems important.
> ENH: Add compressed TSV files to the common principles

- src/modality-specific-files/physiological-and-other-continuous-recordings.md
- src/schema/rules/sidecars/continuous.yaml
Closes #1745
Just for consistency with other datatypes.
> [MAINT] split physio metadata tables

- src/modality-specific-files/task-events.md
- src/schema/rules/checks/events.yaml
> [ENH] events.tsv should be sorted by onset values

- mkdocs.yml
- src/modality-specific-files/physiological-recordings.md
- src/modality-specific-files/task-events.md
This fix builds on #1749 to separate ``_stim`` and ``_physio`` in the specs.
Currently ``_stim`` files are specified sideways as an addon or extra branch of ``_physio``, which can be confusing and misrepresent their intent.
Moving them with the other stimuli definitions increases the consistency of the spec and the findability of ``_stim`` specifications.
This fix requires #1749 for a more consistent prescription of `tsv.gz` files.
> FIX: Move ``_stim.<ext>`` specification within the Task Events module

- tools/schemacode/bidsschematools/tests/test_schema.py
- tools/schemacode/bidsschematools/types/namespace.py
> FIX: Make `namespace.to_dict()` recurse fully

- pdf_build_src/process_markdowns.py
- tools/add_contributors.py
- tools/mkdocs_macros_bids/macros.py
- tools/schemacode/bidsschematools/render/tables.py
- tools/schemacode/bidsschematools/render/text.py
- tools/schemacode/bidsschematools/schema.py
- tools/schemacode/bidsschematools/validator.py
* rmv "infra": ":metro:" as it is a repeat
* fix broken docstrings
* shield mutable default args
None of these changes should affect the actual performance of the library
> code cleanup

- src/appendices/entity-table.md
closes none
Tiny tweak that helps for all tables but that of MRI.
https://bids-specification.readthedocs.io/en/latest/appendices/entity-table.html#biopotential-amplification-eeg-and-ieeg
https://bids-specification--1784.org.readthedocs.build/en/1784/appendices/entity-table.html
> [ENH] use full width entity page

- src/schema/rules/checks/references.yaml
Fixes two issues found in real datasets:
1) ~~`stim_file` columns with all `n/a`. This is already handled in a duplicated check:~~ Guessing this got rebased out before pushing.
2) `IntendedFor` fields with an empty array (`[]`) as a value. Other reference checks suffer the same potential bug, so fixed at the same time.
> SCHEMA: Update existence checks to consider empty lists

- src/schema/rules/sidecars/pet.yaml
In general I like more `(XXXX,YYYY)` form but the other form more prevalent and thus what I also suggested in https://github.com/bids-standard/bids-specification/pull/1450/files
Attention to this was triggered by @CPernet 's comment in
- https://github.com/bids-standard/bids-specification/pull/1450#issuecomment-2028576595
src/schema/objects/metadata.yaml and src/schema/rules/checks/asl.yaml src/schema/rules/sidecars/mri.yaml all use form without `()` and pet sometimes only used with ()
> ENH: Use "Tag XXXX, YYYY" not "Tag (XXXX,YYYY)" for DICOM Tags

- src/common-principles.md
- src/modality-specific-files/physiological-recordings.md
- src/modality-specific-files/task-events.md
- src/schema/objects/extensions.yaml
- tools/schemacode/bidsschematools/render/text.py
origin: 
- https://github.com/bids-standard/bids-specification/pull/1749#discussion_r1545497672
> Make extensions identifiers contain . to separate extensions where multiple used

- .github/workflows/validate_bids-examples.yml
- tools/schemacode/bidsschematools/migrations.py
To minimize "traffic" on bids-2.0 PR
> Bids 2.0: work out testing against bids-examples

- src/appendices/contributors.md
- tools/print_contributors.py
pre-commit is unhappy. Looks like flake8 has started linting the contents of f-strings (more).
> [MAINT] Update contributor table generator style

- src/common-principles.md
- tools/schemacode/bidsschematools/tests/data/expected_bids_validator_xs_write.log
- tools/schemacode/bidsschematools/tests/test_validator.py
- tools/schemacode/bidsschematools/validator.py
Individual commits have more rationale.
I can split into multiple PRs but let's see - may be this could provide us a closure.
Reflecting my thoughts on 
- https://github.com/bids-standard/bids-specification/pull/1734/files#r1534475631
---
- Closes #1736 
- Supersedes #1734
- Closes #1519
> [FIX] Move `rawdata/` into `sourcedata/raw` in alternative structure example, clarify on naming of datasets themselves

- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/schema/rules/checks/electrodes.yaml
- src/schema/rules/files/raw/channels.yaml
In BIDS 1.3, EEG had
```
sub-<label>[_ses-<label>][_acq-<label>][_run-<index>]_electrodes.tsv
```
and iEEG had 
```
sub-<label>[_ses-<label>][_space-<label>]_electrodes.tsv
```
As of 1.5, presumably due to schema stuff, they both became
```
sub-<label>[_ses-<label>][_acq-<label>][_space-<label>]_electrodes.tsv
```
So EEG lost `run` and gained `space`, and iEEG gained `acq`. Looking in OpenNeuro, there are iEEG electrodes files with `acq` and `run` and EEG with `space`. So we should just permit all three for both, as trying to bottle this genie isn't worth the pain.
> FIX: Re-add run entity to electrodes.tsv

- src/metaschema.json
This should be reviewed as two separate commits. The first contains the change I want to make, the second just runs `prettier` to enforce a consistent style.
> [INFRA] Refactor metaschema file rules into definitions

- src/modality-agnostic-files.md
- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/positron-emission-tomography.md
- src/schema/objects/columns.yaml
- src/schema/objects/metadata.yaml
- src/schema/objects/suffixes.yaml
In the vast majority of cases, strict anonymisation is impossible. Use the more generic term deidentification instead.
I suggest #1769 is merged first, then I can rebase and fix all occurrences.
Fixes #1782.
> [ENH] Use deidentification consistently in place of anonymization

- .github/workflows/shellcheck.yml
- .pre-commit-config.yaml
- scripts/test_tag
> [MISC] Add shellcheck checks to ensure that those few shell scripts we have are "robust"

- src/common-principles.md
Currently attempting to revive BEP016, after having had #1003 rejected via #1339 and alternative solution #1280 rejected also.
In #946 I rewrote the Inheritance Principle. Previous text sort of tried to both explain what it was and how it worked and why all together; with that change I focused on defining a set of rules that were both human-readable and actionable for software developers.
However it jumps out at me now that the specification goes straight into those systematized rules with zero introduction of what the Inheritance Principle actually is or why it exists. So here I've tried to give a very succinct explanation. It only needs to be a user-friendly introduction, so doesn't need to be hardcore optimized, happy to take on modifications.
> [ENH] Describe Inheritance Principle in Common Principles

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/objects/suffixes.yaml
- src/schema/rules/files/deriv/imaging.yaml
- src/schema/rules/files/raw/dwi.yaml
> [ENH] Specify the naming of scanner-generated TRACE and ADC volumes

- src/metaschema.json
- src/schema/rules/files/common/tables.yaml
- tools/schemacode/bidsschematools/conftest.py
- tools/schemacode/bidsschematools/data/tests/test_rules.py
- tools/schemacode/bidsschematools/rules.py
- tools/schemacode/bidsschematools/tests/test_rules.py
This PR slightly amends how `stem` rules work, by making the stem a [glob](https://www.man7.org/linux/man-pages/man7/glob.7.html) pattern and allowing it to coexist with `datatype`. This hacks 'phenotype' into the `datatype` structure; in the absence of entities, it works correctly for now.
I don't know that this is a long-term solution, but it seems good enough for now with minimal changes required to the schematools or the JS schema validator.
This is intended to be compatible with, but not actually dependent on #1693.
> SCHEMA: Add file rule for phenotype tables

- .circleci/config.yml
as per: https://support.circleci.com/hc/en-us/articles/23614965074459-2024-Image-Deprecations-and-Brownouts-Android-Linux-VM-Remote-Docker-Linux-VM
see: https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176
We will not see in the CI here whether or not this works, but only once we create a "merge commit" and let the CI run on master.
> Update circleci docker image

- src/schema/rules/checks/dataset.yaml
- src/schema/rules/checks/general.yaml
- src/schema/rules/tabular_data/modality_agnostic.yaml
> fix(schema): Check paths with initial slashes

- src/schema/README.md
- src/schema/meta/expression_tests.yaml
- src/schema/rules/checks/dataset.yaml
- src/schema/rules/checks/events.yaml
- src/schema/rules/checks/mri.yaml
It turns out, in javascript, `[1] != [1]` because equality is object equality. We can either parse the expression language and build an AST or we can add an `allequal()` function and move on with our lives.
@rwblair This is mostly a notice. Feel free to approve, but I'm going to merge in the absence of objections.
> feat(schema): Add allequal(x: array, y: array) to expression language

- .github/pull_request_template.md
Closes none
--- 
- improve readability of PR template message (vertically group list items by topic)
- semantic line break
- add section for BEP PR to include "github admonitions" (started adding those eyetracking BEP and ephys BEP)
> [MAINT] update PR template to include BEP header

- src/schema/rules/checks/hints.yaml
Restores issue `README_FILE_MISSING` to the schema-based validator.
> feat(schema): Add schema check for README file

- DECISION-MAKING.md
- Reducing my hours due to upcoming commitments that won't allow me to stay involved as much as I was
- Based on internal discussions among maintainers, the role of "lead maintainer" will now be rotating among BIDS maintainers
The role description of what a "lead maintainer" is/does and how we rotate that responsibility should become part of the Maintainers Guide.
Furthermore, the content in the "Maintainers Group" section of the `DECISION_MAKING.md` document (edited here) should be migrated to the Maintainers Guide, once it's been merged, see:
- #1770
> MAINT: reduce hours stefan, clarify lead maintainer

- src/modality-specific-files/microelectrode-electrophysiology.md
- src/schema/objects/datatypes.yaml
- src/schema/objects/modalities.yaml
- src/schema/objects/suffixes.yaml
- src/schema/rules/files/raw/channels.yaml
- src/schema/rules/files/raw/ephys.yaml
- src/schema/rules/files/raw/microephys.yaml
Implements 
- https://github.com/bids-standard/bids-specification/issues/1800 .
Didn't want to push to bep032 since not yet agreed upon by @bids-standard/bep032 but wanted to be ready when/if we decide to proceed.
Closes #1800
> BEP032: ephys -> {icephys, ecephys}

- CONTRIBUTING.md
- Release_Protocol.md
documentation for the commit I pushed here: https://github.com/bids-standard/bids-specification/commit/eba3e08e2dbfd3ad2e57c2a52c3bda8c1961dc6c
This PR should be merged only after it has been shown that that commit (☝️ ) actually works ...
see:
- #1852 
Xrefs:
- https://github.com/bids-standard/bids-specification/pull/1836
- https://github.com/bids-standard/bids-specification/pull/1850
> DOC: Updates to how changelog generator is working

- src/introduction.md
- src/modality-specific-files/microscopy.md
- src/schema/objects/columns.yaml
- src/schema/objects/formats.yaml
- src/schema/objects/metadata.yaml
```
sed -i'' -e 's#https://scicrunch.org/resources#https://rrid.site#' src/**/*.{md,yaml}
```
> [FIX] Update links to moved RRID site

- src/common-principles.md
I was under impression that we had such wording somewhere but I failed to find. Such aspect came up during recent presentation by @rordenlab to SC,
<details>
<summary>and we already have lots of metadata fields formalized that way</summary> 
```shell
❯ git grep DICOM | grep -i -e based -e correspond
src/modality-specific-files/magnetic-resonance-imaging-data.md:Volume types are defined in the following table, based on DICOM Tag 0018, 9257 `ASL Context`.
src/schema/objects/metadata.yaml:    Corresponds to DICOM Tag 0018, 9073 `Acquisition Duration`.
src/schema/objects/metadata.yaml:    Based on DICOM Tag 0018, 925F `ASL Bolus Cut-off Delay Time`.
src/schema/objects/metadata.yaml:    Corresponds to DICOM Tag 0018, 925C `ASL Bolus Cut-off Flag`.
src/schema/objects/metadata.yaml: …
```
> [ENH] Add explicit wording on DICOM terms correspondence

- src/modality-specific-files/microscopy.md
- src/schema/objects/suffixes.yaml
- src/schema/rules/files/raw/micr.yaml
Following the discussion at #1646, I am reverting @balbasty's PR #1686 with `XPCT` instead of `hipCT`: it is more suited for a broader audience.
> [FIX] Change hipCT microscopy suffix to XPCT

- src/schema/rules/checks/deprecations.yml
- needed for https://github.com/bids-standard/bids-specification/pull/1310
Code supplied by @effigies in https://github.com/bids-standard/bids-specification/pull/1310#discussion_r1628202915
> Add deprecation check for ElektaNeuromagMEGIN in schema

- src/derivatives/imaging.md
Minor fix to remove an extra parenthesis from the [Discrete Segmentations](https://bids-specification.readthedocs.io/en/stable/derivatives/imaging.html#discrete-segmentations) section:
> [FIX] Remove extra bracket

- .mailmap
Before:
❯ git shortlog -sn 598a6c0749aef0180143b92937d079d9883b9c2e..
...
3  Ben Dichter
2  Dimitri Papadopoulos Orfanos
2  Teon L Brooks
1  Ariel Rokem
1  Dimitri Papadopoulos
After:
❯ git shortlog -sn 598a6c0749aef0180143b92937d079d9883b9c2e.. | grep -v bot
...
3	Ben Dichter
3	Dimitri Papadopoulos Orfanos
2	Teon L Brooks
> Make two Dimitis into one

- .pre-commit-config.yaml
- src/metaschema.json
- src/schema/objects/metadata.yaml
- tools/schemacode/bidsschematools/render/tables.py
`schema.objects.metadata` entries are very nearly JSON schema definitions. To allow BIDS validators to stand on the shoulders of JSON schema validators, the goal of this PR is to define them as JSON schema with extra fields. By doing so, BIDS validators can pass these directly to JSON schema validators along with the pieces of JSON objects that they are intended to validate.
In order to do this, I've tried to formalize the different "kinds" of objects (or terms) we have in composable classes.
The main change to the schema is to rename `required_fields` to `required`, which has the same meaning in JSON schema. Similarly, we update `recommended_fields` to `recommended`, although this will have no impact on validation for now.
> rf(metaschema): Validate object definitions that are JSON schema

- tools/schemacode/bidsschematools/schema.py
> fix(schema): Deduplicate enum values constructed from anyOfs

- src/metaschema.json
- src/schema/objects/columns.yaml
- tools/schemacode/bidsschematools/render/tables.py
- tools/schemacode/bidsschematools/render/text.py
- tools/schemacode/bidsschematools/render/utils.py
In BIDS we have three types of columns:
1) Fully-defined columns, such as `participant_id` or the `type` column in `electrodes.tsv`. These are ones where having JSON-schema style definitions of values is convenient, as we can rely on a well-established way of validating values. There is no good use case for overriding these, since the meaning should not vary from dataset to dataset.
2) Example columns used in the specification, what I am calling "conventional" columns, such as `age` or `handedness`. These are used in the spec and it was decided some time ago that we will let people use them without complaining about being ill-defined, as long as they use them consistently with the specification.
3) User-defined columns are not provided in the specification, and the descriptions of the …
> feat(schema): Provide default JSON column definition for "conventional" columns

- src/modality-specific-files/magnetic-resonance-spectroscopy.md
- src/schema/rules/files/raw/task.yaml
- src/schema/rules/sidecars/mrs.yaml
@markmikkelsen With these patches, your examples in https://github.com/bids-standard/bids-examples/pull/425 pass.
> FIX: Add MRS events files, restrict sidecar metadata checks to data files

- src/schema/rules/sidecars/meg.yaml
Discovered when attempting to validate ds000117 using the JSON schema-snippets in `objects.metadata`. The old JSON schema also made this distinction.
xref https://github.com/bids-standard/bids-validator/pull/2020
> fix(schema): Point to correct DigitizedHeadPoints definition for MEG coordsystem

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/rules/checks/events.yaml
- src/schema/rules/checks/fmap.yaml
- src/schema/rules/checks/func.yaml
- src/schema/rules/checks/nirs.yaml
- src/schema/rules/sidecars/func.yaml
- src/schema/rules/sidecars/mri.yaml
Various fixes found while working through schema validator issues.
> fix(schema): Fix checks to reduce false positives

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/microscopy.md
The link checker failing across the board. awaresystems.be has let their domain lapse, so switching to the Wayback Machine.
> [FIX] Replace defunct awaresystems.be and fslwiki links

- tools/schemacode/bidsschematools/rules.py
- tools/schemacode/bidsschematools/tests/test_rules.py
- tools/schemacode/bidsschematools/tests/test_validator.py
The regexes currently generated by bidsschematools were overly permissive, allowing mismatches between the entities in the directory and the entities in the filename. This was caught because the Python validator moved to depending on bidsschematools, and pybids has an additional battery of checks. (See https://github.com/bids-standard/pybids/pull/1080.)
I've copied the failing checks in here as well as run pybids' test using this branch of bidsschematools.
Really, we shouldn't be using regexes, but doing it right is its own challenge and this fixes a known issue. Further, this does not handle the case where you might have, e.g., `ses-siteA_dwi.json` that applies to one session across all subjects.
<details><summary>For my future reference, to properly implement inheritance in regexes, we …
> fix(regex): Construct backreferences to ensure entity consistency

- src/schema/meta/context.yaml
This is intended to give better guidance to tooling that would auto-generate classes or interfaces for the validation context.
For example, we can run:
<details><summary><code>bst export | jq .meta.context | npx quicktype --src-lang schema --lang ts -t Context --just-types</code></summary>
```typescript
export interface Context {
/**
* Associated files, indexed by suffix, selected according to the inheritance principle
*/
associations: Associations;
/**
* TSV columns, indexed by column header, values are arrays with column contents
*/
columns?: { [key: string]: string[] };
/**
* Properties and contents of the entire dataset
*/
dataset: Dataset;
/**
* Datatype of current file, for examples, anat
*/
datatype?: string;
/**
* Entities parsed from the current filename
*/
entities?: { [key: …
```
> feat(schema): Improve type annotations of schema.context

- src/appendices/arterial-spin-labeling.md
regarding Issue: Background suppression timing for ASL #1842
I've changed 'required' to 'recommended' and slightly reworded the sentence.
Michael
> [FIX] Update text to reflect that BackgroundSuppressionPulseTime is recommended

- src/schema/objects/columns.yaml
Small cleanup to simplify column definitions. `n/a` is valid in ALL columns in a TSV file. We could either add it as an explicitly permitted value to all columns or leave it implicit. I'm going with implicit because it makes for cleaner definitions.
> chore(schema): Remove explicit "n/a" from column definitions

- src/schema/rules/checks/func.yaml
This rule goes counter to the table in https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetic-resonance-imaging-data.html#timing-parameters_1.
> fix(schema): Remove SLICE_TIMING_AND_DURATION_MUTUALLY_EXCLUSIVE

- .github/workflows/publish_schema.yml
- src/schema/meta/context.yaml
- tools/schemacode/bidsschematools/__main__.py
This PR adds a GitHub action that will push dev versions and release versions to https://jsr.io/@bids/schema.
I have been testing this for use in the BIDS validator. Currently we are able to load the [schema](https://jsr.io/@bids/schema/0.0.202408200837/schema.json) from the registry via:
```typescript
import { default as schema } from 'jsr:@bids/schema@0.0.202408200837/schema' with { type: 'json' }
```
We are also able to load the type of the schema with:
```typescript
import type { Metaschema } from 'jsr:@bids/schema@0.0.202408200837/metaschema'
import type { Context }  from 'jsr:@bids/schema@0.0.202408200837/context'
```
The version scheme will be `{schema.schema_version}` if the version is a full release (X.Y.Z), and `{schema.schema_version}.{serial}+{hash}` for development versions. …
> [INFRA] Publish schema to Javascript Registry (https://jsr.io/@bids/schema) on changes and releases

- src/appendices/units.md
Should fix checklinks. We also don't need to be pointing to an ad-supported skin for wikipedia.
I moved the URL definitions out of the table so that URLs can be edited without modifying the width of the table in the future.
> [STY] Use wikipedia links, separate URL definitions

- src/appendices/qmri.md
- src/appendices/units.md
- src/schema/rules/sidecars/fmap.yaml
This PR resolves #1351 by drawing the TotalReadoutTime and MixingTime definitions from the schema. I followed the table in https://bids-specification.readthedocs.io/en/latest/appendices/qmri.html#field-maps to determine the required metadata.
> [FIX] Define a metadata table for TB1EPI

- src/schema/rules/checks/asl.yaml
- src/schema/rules/checks/micr.yaml
- src/schema/rules/checks/mri.yaml
- tools/schemacode/bidsschematools/tests/test_expressions.py
- closes none but relates to https://github.com/bids-standard/bids-specification/pull/1910#issuecomment-2312591610
> [SCHEMA] Check sidecar fields mentioned in rule checks exist in the schema 

- src/modality-specific-files/magnetic-resonance-spectroscopy.md
- src/schema/rules/sidecars/mrs.yaml
- closes #1913 
only did institution info, ran out of motivation to split things further
- also did some minor style and fix in the MRS page
> [MISC] extract MRS institution info in separate table

- src/schema/rules/checks/micr.yaml
@Remi-Gau's fix of our typo'd metadata field revealed an error in the PixelSizeInconsistent check. The main error is that OME-XML uses µm instead of um. I went ahead and also permitted some error to account for inconsistent serialization/floating point error.
> fix(schema): Update microscopy pixel size checks to account for error and OME convention

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/objects/suffixes.yaml
- src/schema/rules/files/deriv/imaging.yaml
- src/schema/rules/files/raw/dwi.yaml
Reverts bids-standard/bids-specification#1725 because there is an intent to replace it with https://github.com/bids-standard/bids-specification/pull/1864.
If #1864 is not accepted in time for 1.10.0, then this will be merged so that it can come in a later release without backwards compatibility issues.
> Revert "[ENH] Specify the naming of scanner-generated TRACE and ADC volumes"

- src/modality-specific-files/behavioral-experiments.md
- src/schema/rules/tabular_data/task.yaml
Part two of resolving https://github.com/bids-standard/bids-validator/issues/1376. Also provides a starting point for behavioral files, instead of being purely free-form. If someone's going to use columns that are defined for `events.tsv`, they should mean the same thing in `beh.tsv`.
> [ENH] Provide baseline definition for behavioral files

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/objects/columns.yaml
- src/schema/objects/enums.yaml
- src/schema/objects/metadata.yaml
- src/schema/rules/files/raw/perf.yaml
Closes #1762, but does not fully describe control-like "dummy" scans.
- Allow `noRF` and `n/a` as allowed `volume_type` values in aslcontext files.
- Allow `noRF` as a suffix for perfusion data.
- Allow `echo` and `part` entities for `_asl` and `_m0scan` files.
> [ENH] Add noRF and n/a ASL volume types

- src/modality-agnostic-files.md
- src/schema/rules/dataset_metadata.yaml
xref https://github.com/bids-standard/bids-examples/pull/426 https://github.com/bids-standard/bids-validator/issues/1959
Closes https://github.com/bids-standard/bids-validator/issues/1581.
> fix(schema): Authors is recommended if CITATION.cff is absent

- tools/examplecode/example.py
Without that users must have trailing / removed, but nobody checks for that etc. So now we have "raw//" etc, e.g. at
https://bids-specification.readthedocs.io/en/latest/derivatives/common-data-types.html#example-use-of-a-descriptionstsv-file
With this change it would make it easier on user and guaranteed to render consistently correctly
> Strip possibly present trailing / (os.sep) before adding one

- src/schema/rules/checks/mri.yaml
- src/schema/rules/sidecars/entity_rules.yaml
- src/schema/rules/sidecars/mri.yaml
Starting with a trigger-happy `BOLUS_CUT_OFF_DELAY_TIME_NOT_MONOTONICALLY_INCREASING`.
Fixes https://github.com/bids-standard/bids-validator/issues/2128.
> [SCHEMA] Fixes identified from reviewing OpenNeuro errors

- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/intracranial-electroencephalography.md
- src/modality-specific-files/magnetoencephalography.md
- src/modality-specific-files/near-infrared-spectroscopy.md
- src/schema/rules/checks/channels.yaml
- src/schema/rules/files/raw/channels.yaml
We've run into a situation where the regular validator regular expressions were written more laxly than the specification, leading to datasets that use entities that are against the spec but perfectly interpretable. In particular, the `task` entity has been permitted for `coordsystem.json` across EEG, iEEG, MEG and NIRS.
Following the pattern established in #1722, instead of marking these datasets invalid with a schema-based validator, we relax the spec but add warnings.
cc @bids-standard/raw-electrophys and @rob-luke @lpollonini (we should make a NIRS team...).
> [FIX] Allow (but discourage) task, acquisition and run entities for coordsystem.json and electrodes.tsv

- src/schema/README.md
Looks like some table ordering is a bit mixed up in
https://bids-specification.readthedocs.io/en/latest/schema/#ordering-rules
TODO
looks now with the fix:
> Add an empty line in hope to get table rendered properly in "Ordering ..." section

- src/schema/rules/files/raw/task.yaml
Issue outlined in bids-standard/bids-validator#2164
This would fail to cover echo, part, and chunk entities which are legal for anatomical images and so too would be legal in the physio filenames.
> [SCHEMA] Allow physio files for anat datatype

- CONTRIBUTING.md
- macros_doc.md
- closes #1932 : actually only silence the rendering of macro in the doc about macros
- closes #1934 : remove sections that exist in the common contributing
> [REF] refactor contributing documentation

- src/common-principles.md
> Include entity-less "scans.json" into an example of inheritance principle

- src/schema/objects/columns.yaml
> [ENH] Add interpretation of "n/a" onsets in events.tsv files

- mkdocs.yml
RTD deprecated google analytics:
https://github.com/readthedocs/readthedocs.org/issues/11707
Added GA id to mkdocs config as per:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
> [INFRA] add GA ID to mkdocs config

- tools/schemacode/bidsschematools/data/tests/test_rules.py
- "explicit better than implicit" especially in case of tests
when test fails - very hard to debug. hopefully more of checks would help
> Add a few more tests for the schema

- src/modality-specific-files/intracranial-electroencephalography.md
- src/schema/objects/extensions.yaml
- src/schema/rules/files/raw/ieeg.yaml
Added MED format
- closes #1931
> [ENH] Allow MED format for iEEG data (`*_ieeg.medd/`)

- tools/schemacode/bidsschematools/__main__.py
- tools/schemacode/bidsschematools/utils.py
This is a basic validator that accepts a `.bidsignore` list and a list of files. The use case is to quickly determine if a git push should be accepted by a server.
> feat(cli): Add tool for filename validation for use in pre-receive hooks

- src/schema/meta/versions.yaml
This PR adds BIDS version 1.10.0 to `src/schema/meta/versions.yaml` to address the following bug:
The `bids-validator` throws an `UNKNOWN_BIDS_VERSION` warning for datasets with `"BIDSVersion" : "1.10.0"`
> [SCHEMA] Add v1.10.0 to known BIDS versions list

- src/schema/objects/formats.yaml
- src/schema/objects/metadata.yaml
- tools/schemacode/src/bidsschematools/tests/test_schema.py
As noted in #1968 and https://github.com/bids-standard/bids-validator/issues/131, we fail to validate timestamps with the `Z`, but instead permit arbitrary 2-4 character upper-case strings. This goes against what the spec actually says.
This PR narrowly brings the schema into line with the text of BIDS 1.10.0. In #2001, I propose permitting the full range of RFC3339 values to handle needs for non-zero offsets.
> fix: Update datetime definition/regex to match specification

- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/schema/objects/metadata.yaml
- src/schema/rules/checks/asl.yaml
- src/schema/rules/sidecars/mri.yaml
- src/schema/rules/sidecars/mrs.yaml
- src/schema/rules/sidecars/pet.yaml
Should fix failing link checks. Then semi-automatically added links to all DICOM tags following the pattern `DICOM Tag \d{4}, \d{4}`. Adjusted newlines when necessary, but did not aim for beauty.
> [INFRA] Fix dicomlookup links, link consistently

- mkdocs.yml
- src/derivatives/imaging.md
- src/modality-specific-files/behavioral-experiments.md
- src/modality-specific-files/electroencephalography.md
- src/modality-specific-files/magnetic-resonance-imaging-data.md
- src/modality-specific-files/magnetoencephalography.md
- src/schema/objects/entities.yaml
- src/schema/rules/json/meg.yaml
- closes https://github.com/bids-standard/bids-specification/issues/2003
> [FIX] update some internal links

- mkdocs.yml
- tools/schemacode/src/bidsschematools/types/namespace.py
> [FIX] graceful error when failing to load invalid yml

- src/common-principles.md
- tools/schemacode/src/bidsschematools/__main__.py
Up to this point it was up for a validator to "code" that up. E.g. current new deno based validator in
https://github.com/bids-standard/bids-validator/blob/main/src/files/ignore.ts has
const defaultIgnores = [
'.git**',
'.*',
'sourcedata/',
...
thus ignores all dotfiles from validation.  But this is inconsistent e.g.  with shipped in bids-specification schematools treatment, where files in a dotdirectory were reported as "invalid":
❯ cat /tmp/input.txt | python -m bidsschematools pre-receive-hook
.datalad/config
.gitattributes
sub-01/anat/sub-01_unknown.nii.gz
And as demonstrated above there could be legit "system" dotfiles (VCS related etc) which are part of the folder containing BIDS dataset, I think we should **explicitly** describe position of BIDS in relation to the dotfiles.  As it …
> [ENH] Do explicitly "allow" for having dotfiles and explicitly ignore them

- src/common-principles.md
as they should be applicable also to numeric values.
- Fixes #1938
> [FIX] Move description of "n/a" above "String values" to avoid any association

- .circleci/config.yml
Currently check fails
URL        `https://www.incf.org/'
Name       `INCF'
Parent URL file:///home/circleci/project/site/introduction.html, line 1795, col 2
Real URL   https://www.incf.org/
Check time 0.084 seconds
Result     Error: SSLError: HTTPSConnectionPool(host='www.incf.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certifica...
possibly due to outdated collection of root certificates in the env where testing?
dunno, but we better address it since it brings overall CI to red quite often, causing fatigue and increasing likeliness to skip important issues.
edit: also sorted lines there for consistency etc
> [INFRA] Ignore www.incf.org link check.. unlikely to go away (hopefully)

- src/common-principles.md
- src/introduction.md
- src/longitudinal-and-multi-site-studies.md
- src/modality-agnostic-files.md
I was getting those locally.
Not sure why they are not caught in CI.
> [STY] fix some remark warnings

- .codespellrc
- src/schema/README.md
- src/schema/objects/metadata.yaml
- tools/schemacode/src/bidsschematools/validator.py
CI started to error out codespell as I saw in #2032 and it is due to new codespell 2.4.0.
So this PR fixes those detected with codespell 2.4.0 and indeed we had inconsistencies on GB vs US forms for "localization" so it is harmonized now.
I have done `HEP` exclusion via regex which might slow things down but would keep it case specific
> [FIX] Run codespell 2.4.0 throughout fixing few left typos automagically

- README.md
- src/common-principles.md
- src/index.md
The DOI [10.5281/zenodo.3686061](https://doi.org/10.5281/zenodo.3686061) only covers versions <= 1.8.0. For versions >= 1.9.0, the correct record is [10.5281/zenodo.10175845](https://doi.org/10.5281/zenodo.10175845).
> [FIX] Update zenodo DOI from 3686061 to 10175845

- src/modality-specific-files/microelectrode-electrophysiology.md
Fixing the BEP 032 markdown 
Changes:
1. Using MACROS___make_sidecar_table instead of specifying every item 
2. Fixing Table of contents
> [FIX] Bep032 - fixing Markdown 

- README.md
This might ease people finding ongoing efforts
Side purpose: see how CI reports success for demonstration of
- #2032
> Point to page with BEPs in README for "more to come in the future"

- src/schema/rules/files/deriv/preprocessed_data.yaml
- tools/schemacode/src/bidsschematools/schema.py
Fixes #2029, to accommodate the `desc` entity (based on the current [derivative specifications](https://bids-specification.readthedocs.io/en/stable/derivatives/introduction.html#file-naming-conventions), for **channels**, **electrodes**, **coordsystem** and **events** files.
I was not sure if adding `description` to `channels.channel` would be inherited to other special cases, such as `channels.channels__motion`, so I explicitly included those in the schema as well.
@effigies, I appreciate your insights.
> [FIX] Permitting `desc` for channels and events

- src/schema/objects/columns.yaml
- src/schema/objects/enums.yaml
Adds microephys enums to `src/schema/objects/enums.yaml`, 'microephys' tags to existing relevant enums and then enlists them `src/schema/objects/columns.yaml `for `type__channels`. 
Contributes to TODOs for #1705
> [BEP032] [SCHEMA] Channel enums for microephys

- src/modality-agnostic-files.md
- src/schema/objects/files.yaml
- src/schema/rules/files/common/core.yaml
Allow extension for the LICENSE file: #2021
> [ENH] Allow LICENSE files to have .txt, .md, or .rst extensions

- src/appendices/qmri.md
- src/schema/rules/sidecars/qmri.yaml
This updates the schema in the maintenance branch, as this does not change the meaning of the specification. This also fixes a minor bug in the specification text, although we don't have a method to rerender it.
Fixes #2018.
> feat(schema): Encode qMRI metadata requirements

- tools/schemacode/pyproject.toml
It turns out that the tool [bump-my-version](https://callowayproject.github.io/bump-my-version/) can handle our tagging strategy for the bidsschematools. Here is a configuration that captures the workflow I've been doing by hand.
I did recently add `tool.bumpver`, but it couldn't handle tags due to the need for a `schema-` prefix.
I added the release process in a comment, but I'm happy to update a doc if there is one.
> chore(schematools): Add configuration for bump-my-version

- src/schema/objects/metadata.yaml
Schema error detected by the AJV validator attempting to validate ScreenSize/ScreenResolution in OpenNeuro datasets. Warnings were being emitted that invalidated the JSON output.
Targeting the `maint/1.10.0` branch so this can be fixed and released in schema before the next BIDS release.
xref https://github.com/bids-standard/bids-validator/pull/166
> fix: Use of min/maxItems in types of ScreenSize/ScreenResolution

- .circleci/config.yml
We know they are broken:
- https://github.com/bids-standard/bids-specification/issues/2068 
and there is no immediate fix. This should disable them, until we resolve them, and do not miss some other broken urls interim (e.g. while reviewing https://github.com/bids-standard/bids-specification/pull/2064 by @Remi-Gau ).
> Temporarily disable dicomlookup urls check

- tools/schemacode/src/bidsschematools/__main__.py
- tools/schemacode/src/bidsschematools/utils.py
We tried to upgrade to use recent bidsschematools in dandi-cli (https://github.com/dandi/dandi-cli/pull/1591) but tests started to fail since output was polluted with log messages from bidsschematools, which prompted me to look inside.
I have tried to keep my changes minimal (but did rename `logger` to `lgr` for consistency) and individual commits provide a little more information, but overall point - do not configure logger unless it is an "end user application". And it is typical for logging to just go into stderr to not interfere with potential "useful" output on stdout.
> fix(bst): Do not alter logger in library mode, log to stderr not stdout

- tools/schemacode/src/bidsschematools/schema.py
This PR corrects the type annotation and description of the return type of `load_schema()` in `schema.py` in `bidsschematools`. Please see individual commits for details of the changes.
> [FIX] correct return type documentation of `load_schema()` in `bidsschematools`

- src/common-principles.md
- src/schema/rules/directories.yaml
- src/schema/rules/files/common/core.yaml
It is quite often desired to store logs, e.g. simply stdout/stderr from invocation of BIDS converters or other tools which were used to produce/change content in current BIDS datasset.  They quite often provide ultimate provenance information to troubleshoot odd or incorrect results.  But researchers, in my personal opinion, undervalue logs!  But hinting them on "standard" location for them, I think we could inspire more of relevant to dataset provenance metadata being collected and shared.  
TODOs:
- ~~?Danger: might leak sensitive metadata, so may be wording should be adjusted to mention that they should be inspected/sensored? WDYT?~~ I think it is fine/assumed
Shameless plug: consider using con-duct (https://github.com/con/duct) for your "logging needs".
Note that I think that ideally …
> [ENH] Formalize presence of optional logs/ folder

- src/modality-specific-files/intracranial-electroencephalography.md
In the example:
1. Modality `ieeg` was missing from the filetree
2. `sub` and `ses` in the photo prefix didn't match the actual names
3. Remove unintended break
> [FIX] Fix typos in specification about iEEG photo

- src/schema/objects/entities.yaml
While working through BEP38 stuff, we saw the "space" entity definition reads more restrictive than it has generally been validated, and is overly-specific to the first few data types accepted into BIDS.
In particular,
> The `<label>` MUST be taken from one of the modality specific lists in the Coordinate Systems Appendix.
conflicts with the common derivatives specification that `SpatialReference` MUST be provided if `<label>` *is not* found in that list.
This update aims to be a bit more general while noting that additional restrictions may apply to the values of `<label>` in some cases.
> [!Tip]
>
> [**HTML preview of this PR**](insert URL to HTML preview once available)
>
> [ENH] Clarify definition of space entity

- src/common-principles.md
- src/schema/rules/directories.yaml
- src/schema/rules/files/common/core.yaml
Inspired by the success of the
https://github.com/bids-standard/bids-specification/pull/1962 adding formalization of `logs/` folder, and triggered by the use-case in DANDI https://github.com/dandi/dandi-docs/pull/200 seeking to add more elaborate descriptions to the README (or more specifically README.md), I would like to propose adding any extra documentation and associated artwork (images, videos, etc) under `docs/` folder.  I do not think it is worth breaking down more (as videos/) etc, since it could confuse with data types (videos of behavior or alike).
Not sure if we would want to formalize inner structure anyhow. We could potentially recommend using `docs/images/` subfolder for images.
Then README.md on top level could potentially use those images via references to `docs/` paths. …
> [ENH] Formalize presence of optional docs/ folder

- .circleci/config.yml
- src/modality-specific-files/magnetic-resonance-imaging-data.md
ATM we have CI red because of
```
...
URL        `https://lcni.uoregon.edu/wiki/acquiring-and-using-field-maps/'
Name       `Acquiring and using field maps - LCNI'
Parent URL file:///home/circleci/project/site/modality-specific-files/magnetic-resonance-imaging-data.html, line 2908, col 1
Real URL   https://blogs.uoregon.edu/lcni/wp-login.php?privacy=1&redirect_to=https%3A%2F%2Fblogs.uoregon.edu%2Flcni%2Fwiki%2Facquiring-and-using-field-maps%2F%2F
Check time 0.804 seconds
Warning    [http-redirected] Redirected to
`https://blogs.uoregon.edu/lcni/wp-login.php?privacy=1&redirect_to=https%3A%2F%2Fblogs.uoregon.edu%2Flcni%2Fwiki%2Facquiring-and-using-field-maps%2F%2F'
status: 302 Found.
Result     Valid: 200 OK
1 thread active,    12 links queued, 1154 links in 1168 URLs checked, runtime 1 …
```
> [BF]: use web archive link for now gone behind login page about fieldmaps

- .github/workflows/schemacode_ci.yml
- .gitignore
- .pre-commit-config.yaml
- tools/schemacode/MANIFEST.in
- tools/schemacode/pyproject.toml
- tools/schemacode/setup.cfg
- tools/schemacode/src/bidsschematools/__init__.py
- tools/schemacode/src/bidsschematools/__main__.py
- tools/schemacode/src/bidsschematools/conftest.py
- tools/schemacode/src/bidsschematools/data/__init__.py
- tools/schemacode/src/bidsschematools/schema.py
- tools/schemacode/src/bidsschematools/tests/data/__init__.py
- tools/schemacode/src/bidsschematools/tests/test_schema.py
- tools/schemacode/src/bidsschematools/tests/test_validator.py
- tools/schemacode/src/bidsschematools/types/namespace.py
- tools/schemacode/src/bidsschematools/validator.py
This PR is some house-keeping before some larger changes I would like to make to the bidsschematools package. Those changes include switching to PDM for writing build hooks to install a compiled JSON schema in the package. To do that, we need to switch to pyproject.toml, at which point we should probably drop Python 3.8 support and use the [acres](https://pypi.org/project/acres/) package to abstract away `importlib_resources`.
> rf(schemacode): Update packaging, minimum Python, resource loading

- src/schema/rules/checks/dataset.yaml
I could be wrong but I think there is no strict and agreed upon requirement to require having sub- subfolders in BIDS specification. Although odd, thus warranting a warning, I think it is not strictly forbidden, and e.g. a BIDS dataset only with stimuli/ or derivatives/ or sourcedata might still be well legit BIDS dataset.
Check was added in b9ea963df27ded2c4363199c4c030c0229f2d1e2 likely just copying from prior node version of bids-validator.  Asking @effigies for setting me straight ;)
> Downgrade absence of sub- folders to warning

- tools/schemacode/pdm_build.py
- tools/schemacode/pyproject.toml
- tools/schemacode/src/bidsschematools/__init__.py
- tools/schemacode/src/bidsschematools/__main__.py
- tools/schemacode/src/bidsschematools/schema.py
- tools/schemacode/src/bidsschematools/types/namespace.py
In https://github.com/bids-standard/python-validator/pull/2, I'm generating classes on the fly from `schema.meta.context`. As it stands, the import takes about 530ms on my machine, about 470ms of it spent loading the schema and constructing the classes.
This change builds `schema.json` during the Python packaging process and includes it instead of the YAML directory inside the tarball and wheel. Along with deferring a couple imports (here and in #2109), this brings the import time down to about 35ms, with 10ms spent on loading the schema and building the classes.
Editable installs are left loading YAML files, to avoid caching an old state.
> feat: Compile schema.json and bundle in Python package

- src/schema/objects/common_principles.yaml
- src/schema/objects/datatypes.yaml
- tools/schemacode/src/bidsschematools/__main__.py
- tools/schemacode/src/bidsschematools/data/tests/test_rules.py
Closes #1828. Please continue the conversation in that issue, and reserve this PR for discussing concrete changes.
> [ENH] Define "phenotype" as a data type not nested inside subjects

- .github/workflows/schemacode_ci.yml
- tools/schemacode/pyproject.toml
Before:
```
bids-specification/tools/schemacode $ python3 -m build
bids-specification/tools/schemacode $ tar -tzvf dist/*.gz | grep git
-rw-r--r-- 0/0               2 2025-05-16 10:53 bidsschematools-1.1.0.dev0/.gitignore
-rw-r--r-- 0/0              15 2025-05-16 10:44 bidsschematools-1.1.0.dev0/tests/data/.gitignore
```
After:
```
bids-specification/tools/schemacode $ git clean -fxd
bids-specification/tools/schemacode $ python3 -m build
bids-specification/tools/schemacode $ tar -tzvf dist/*.gz | grep git
(no output)
```
> [MISC] In bidsschematools, exclude .gitignore files from sdists

- src/common-principles.md
links checker started to fail, and I see
❯ wget -S https://www.mathworks.com/matlabcentral/fileexchange/42997-xiangruili-dicm2nii
--2025-05-21 16:18:06--  https://www.mathworks.com/matlabcentral/fileexchange/42997-xiangruili-dicm2nii
Resolving www.mathworks.com (www.mathworks.com)... 23.197.176.176
Connecting to www.mathworks.com (www.mathworks.com)|23.197.176.176|:443... connected.
HTTP request sent, awaiting response...
HTTP/1.1 503 Service Unavailable
and in the browser I see "no healthy upstream" for that URL.
https://github.com/xiangruili/dicm2nii was indeed last updated 9 months ago and overall IMHO just a very basic (no unittests etc) project.  I think standard should not promote/point to tools which are not developed with active participation in the project. dcm2niix is actively …
> Remove reference to dicm2nii altogether and point to page with more converters

- src/schema/meta/context.yaml
- src/schema/rules/checks/dataset.yaml
- src/schema/rules/checks/phenotype.yaml
This builds on and takes advantage of #2050 to select phenotype files and compare the `participant_id` column to the dataset-global `dataset.subjects.participant_id`, which is populated from `participants.tsv`.
This does two things for validation implementations:
1) It allows the specific phenotype file with extra participants to be identified, since the phenotype participants are not collapsed into one superset.
2) It allows us to avoid calculating the union at validator startup, which could be potentially costly for files with many phenotype files, as well as avoid loading each phenotype file twice (or hold a long-lived cache of all phenotype data).
Note that #2050 is not strictly required in order to use this check, as validating phenotype file names already requires us to have it as a …
> feat(schema): Rewrite PHENOTYPE_SUBJECTS_MISSING to run on each phenotype file

- src/metaschema.json
- src/schema/rules/tabular_data/derivatives/common_derivatives.yaml
- src/schema/rules/tabular_data/pet.yaml
Several table definitions were missing an indication of whether additional columns were allowed, which defaults to `not_allowed`. This PR updates the metaschema to require the field to be explicit, and sets its value to `allowed_if_defined` for all cases that were missing.
cc @melanieganz @CPernet @mnoergaard for your thoughts on the PET cases. This is strictly speaking a relaxation, but IMO if people provide definitions, that's good?
Closes #1993.
> [ENH] Allow additional columns if defined for various TSV files

- src/modality-specific-files/intracranial-electroencephalography.md
- src/schema/objects/extensions.yaml
- src/schema/rules/files/raw/ieeg.yaml
This reverts commit 436d7cde4c4f5edce4d57085d36ab457e51da6e3.
Adding this format needs additional vetting, per steering group decision.
> Revert "[ENH] Allow MED format for iEEG data (`*_ieeg.medd/`) (#1956)"

- src/schema/rules/tabular_data/modality_agnostic.yaml
Incorporates #2125, and defines `phenotype/*.tsv` files, which are currently unvalidated.
This is targeting the `maint/1.10.0` branch as a schema fixup, not a change to the spec.
> feat: Define phenotype/*.tsv in schema, add HED to modality agnostic tables

- src/metaschema.json
- src/modality-specific-files/intracranial-electroencephalography.md
- src/schema/meta/associations.yaml
- src/schema/meta/context.yaml
- src/schema/rules/checks/channels.yaml
- src/schema/rules/checks/ieeg.yaml
The original iEEG spec intended electrodes.tsv to be REQUIRED, but the language was unintentionally softened during the inclusion in BIDS. This PR clarifies the language, and adds a validation rule to enforce the presence of electrodes.tsv files. Paired with https://github.com/bids-standard/bids-validator/pull/207, this will support detecting multiple electrodes.tsv files that are distinguished by the `space-<label>` entity.
This PR also adds a check that each electrodes.tsv file has a corresponding coordsystem.json file. This was already enforced for optodes.tsv in NIRS datasets, but was missing for electrodes.tsv in *EG datasets.
This follows extensive discussion in https://github.com/bids-standard/bids-validator/issues/206.
Closes …
> [ENH] Clarify that electrodes.tsv are REQUIRED for iEEG data

- src/derivatives/introduction.md
The [derivatives introduction](https://bids-specification.readthedocs.io/en/stable/derivatives/introduction.html) demonstrates a defaced T1w file as `derivatives/sub-01/sub-01_desc-defaced_T1w.nii`, which places it directly under the derivatives folder.  According to [this](https://bids-specification.readthedocs.io/en/stable/common-principles.html#storage-of-derived-datasets) it should however be in a subfolder corresponding to the pipeline name, so a directory name like `derivatives/<pipeline>/sub-01/sub-01_desc-defaced_T1w.nii`.
I named the pipeline "defaced" and inserted it in the example file path. I also renamed the `sourcedata/private` directory into `sourcedata/defaced`. 
Closes #2134.
> Defaced derivative example should be in a pipeline subdirectory

- src/common-principles.md
- src/schema/objects/formats.yaml
- tools/schemacode/src/bidsschematools/tests/test_schema.py
As discussed in #1968, non-UTC timezones can be useful for coordinating acquisitions across time zones. The spec currently adopts RFC3339 with the exception that nonzero UTC offsets are not permitted, and the `Z` offset is optional to allow indicating local time.
For backwards compatibility, I propose allowing the offsets to remain optional, but permitting the full range of RFC3339 offsets.
Separately, the current regular expression does not express the current rule, so I will open another PR against the maintenance branch for that.
> [ENH] Accept UTC offsets in datetimes

- src/common-principles.md
Re-commit of b7a3ab625a7c1994d3984f3eb79c4811449e7e2b that was rejected as a late addition to #1807; re-posting here for separate review as suggested.
I've become progressively convinced that the ability to overload metadata fields via Inheritance is a major source of the disparity in opinions about the Inheritance Principle. Regardless of whether you like or hate it, where I think there should be consensus is that overloading should not be intentionally used, even if BIDS 1.x explicitly permits it and it was used as one of the key demonstrative examples.
The proposed change hopefully also helps to contextualise why the subsequent text is a complex but necessary set of rules.
> Inheritance Principle: Advise against value overloading. Plan to deprecate support for overloading for BIDS 2.0

- src/schema/objects/metadata.yaml
The DICOM tag (0018,9081) is a boolean value, not a partial Fourier fraction.
This implements a discussion between @agahkarakuzu and @neurolabusc in https://github.com/bids-standard/bep001/issues/85.
Closes gh-2110.
> [FIX] Remove incorrect DICOM correspondence of PartialFourier

- .circleci/config.yml
- .github/dependabot.yml
- .gitignore
- CONTRIBUTING.md
- pyproject.toml
- readthedocs.yml
- requirements.txt
- src/schema/README.md
- tools/schemacode/.readthedocs.yaml
- tools/schemacode/docs/_templates/module.rst
- tools/schemacode/docs/conf.py
- tools/schemacode/docs/requirements.txt
- tools/schemacode/pyproject.toml
- uv.lock
This turns the build process from:
```console
$ python -m pip install --upgrade pip
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install -r requirements.txt -e tools/schemacode[render]
$ mkdocs serve
```
```console
$ uv run mkdocs serve
```
> [INFRA] Use uv to manage the build environment

- .gitignore
- pyproject.toml
- tools/schemacode/docs/conf.py
- tools/schemacode/docs/index.rst
- tools/schemacode/docs/quickstart.md
- uv.lock
This adds a jupytext notebook that can be also used as a RISE slideshow to introduce the basic interface of the `bidsschematools` package. Its target is downstream schema users.
Rendered: https://bidsschematools--2147.org.readthedocs.build/en/2147/quickstart.html
> doc: Add quickstart tutorial to bidsschematools site

- .github/workflows/schemacode_ci.yml
- tools/schemacode/docs/conf.py
- tools/schemacode/pdm_build.py
- tools/schemacode/src/bidsschematools/types/_generator.py
- tools/schemacode/src/bidsschematools/types/context.py
- tools/schemacode/src/bidsschematools/types/protocols.py
- tools/schemacode/tests/test_context_types.py
This PR follows-up #2115 by procedurally generating Python types from the `schema.meta.context` object. This uses [structural subtyping](https://typing.python.org/en/latest/spec/protocol.html#protocols) to allow for a variety of implementations to satisfy type-checkers, while also providing default standard library dataclass implementations.
The dataclass fields are annotated with protocols instead of one another, so that you can flexibly mix-and-match the provided dataclasses and your own classes, for example:
```python
from functools import cached_property
import json
import attrs
from bidsschematools.types import context as ctx
@attrs.define
class Dataset:
tree: FileTree
ignored: list[str]
@cached_property
def dataset_description(self) -> dict[str, Any]:
with …
```
> feat: Generate context types from schema

- .circleci/config.yml
- src/appendices/contributors.md
Linkchecker got damaged by #2127. Was easy to overlook given that it fails all the time anyway. Will try to fix broken links before merging...
> fix: Use uvx linkchecker

- src/schema/meta/associations.yaml
- src/schema/rules/checks/events.yaml
Addresses https://github.com/bids-standard/bids-validator/issues/213.
The problem was that in `task in entities`, `task` is an identifier instead of a string, so it always evaluated `false`. The other fix helps in cases where, e.g., there is `channels.tsv` but `run-X_events.tsv`, which means that events aren't found by inheritance for those files.
> fix(schema): Quote task in events association

- src/schema/rules/files/deriv/preprocessed_data.yaml
- src/schema/rules/files/raw/anat.yaml
Closes none.
- Split MESE and MEGRE suffix entity sets.
- Add optional direction entity to the raw MESE anatomical suffix.
> [ENH] Allow direction entity in MESE files

- src/schema/meta/context.yaml
- src/schema/objects/entities.yaml
- src/schema/rules/checks/nifti.yaml
- tools/schemacode/tests/test_context_types.py
The BIDS convention is to use `dir-{AP,PA,LR,RL}` for phase-encoding directions in MRI filenames, as well as `PhaseEncodingDirection` in JSON sidecars. This duplication has the potential for inconsistency or multiple interpretations of the meaning of AP.
This PR aims to clarify the meaning of `dir-<label>` when its value matches a cardinal axis, and clearly state that this meaning SHOULD be consistent with the `PhaseEncodingDirection`.
> [ENH] Specify that dir-<label> should correspond to PhaseEncodingDirection

- src/schema/objects/metadata.yaml
Following up on decision made in Copenhagen. This "is" was interpreted by some to be a requirement, but this has never been validated, would be breaking to turn into an error, and is impractical to encode in the schema. Rather than contort ourselves to devise a check, it makes more sense to use RFC 2119 language to make clear that this is an optional convention, not a requirement.
Closes #2081.
> [ENH] Clarify that task label is not required to derive from TaskName

- src/modality-specific-files/microelectrode-electrophysiology.md
- src/schema/rules/checks/microephys.yaml
- src/schema/rules/files/raw/channels.yaml
- src/schema/rules/files/raw/photo.yaml
- src/schema/rules/json/microephys.yaml
Contributes to #1705 
* 4395dcf3 2025-09-04 | Probe interface exaple file tree
* 2f3069f9 2025-09-04 | Minor change to the default probe relative coordinate system
* cf3e7a95 2025-09-04 | Rewrote the coordsystem JSON and photo section to align with ieeg but adopt to animal electrophysiology
* 198e3655 2025-09-04 | Added entities for the photo specific to microephys
* cfd64cc4 2025-09-04 | Added rules to 1) override rule for coorsystem to be present for electrode.tsv 2) If coorsystem present, corresponding electrode.tsv must be present 3. Match the space between corresponding coordystem and electrodes files
* b84bd493 2025-09-04 | Add coordinate system metadata fields for microephys
* 649a2ce9 2025-09-04 | Adds space entity for microephys electrodes
> [ENH][BEP032] Updates

- mkdocs.yml
- src/css/dynamic-width.css
In many cases, our content is naturally wider than our theme (mkdocs-material) handles comfortably. Filename templates and metadata tables are frequently a bit squashed feeling.
This PR sets the max-width of the content pane to `fit-content` instead of `61rem`. I believe this will always be the same as using the full screen width, but at least allows the possibility that a page with narrow contents would be better centered.
Relates somewhat to #1784, which addressed the impact of the narrow content frame on the entity tables.
References:
* https://github.com/squidfunk/mkdocs-material/discussions/6404
* https://developer.mozilla.org/en-US/docs/Web/CSS/max-width
> [INFRA] Use full page width
