src/99-appendices/03-hed.md
closes #33 
@VisLab see your changes here.
=> update HED appendix

src/99-appendices/01-contributors.md
Added talks and tools contributions for self (T Nichols)
=> Updated my contributions

LICENSE
I couldn't find any reference to the licence for the specification itself in the github repo but the google doc had a CC-BY 4.0. If that's still the case then here's a little license file to make that clearer for new folks 😸
=> Add CC-BY 4.0 license

src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
As discussed https://github.com/bids-standard/bids-specification/issues/63
=> Added CBV contrast

src/99-appendices/01-contributors.md
Based on utilization of BIDS within ReproNim and testing of BIDS in other communities (SPARC). Also developed ReproNim BIDS tutorial presented at OHBM and SfN during ReproNim training course.
=> Added contributor information

src/06-extensions.md
=> repair links

src/02-common-principles.md
Somehow forgotten change proposed by @tyarkoni in https://groups.google.com/d/msg/bids-discussion/WonpwZ8zoUo/8Pnb8iPDGAAJ. Previously signed off by @nicholst, @satra, and @francopestilli.
=> Global fields in data dictionaries

Release_Protocol.md
This aligns with GitHub conventions better.
=> Update tag naming convention

CONTRIBUTING.md, pull_request_template.md
=> [INFRA] Adding instructions for naming PRs

src/99-appendices/06-meg-file-formats.md
=> [FIX] clarify use of tools for CTF data renaming

src/02-common-principles.md
closes #190 
@pvdemael I hope this clarifies what you wanted to address.
=> [FIX] clarify example 3  in common principles (inheritance)

src/99-appendices/02-licenses.md
=> [FIX] Clarify Appendix II: The list of licenses only lists examples

src/04-modality-specific-files/02-magnetoencephalography.md, src/04-modality-specific-files/03-electroencephalography.md, src/04-modality-specific-files/04-intracranial-electroencephalography.md
removed preprint references and replaced with peer-reviewed citations
... also improved consistency between references for EEG, MEG, iEEG
=> [MISC] update modality references

Pipfile.lock
As requested by @effigies in https://github.com/bids-standard/bids-specification/pull/265#discussion_r303552811
The instructions for the pipenv workflow are in #211.
=> [INFRA] Update pipenv

src/02-common-principles.md
Fix `Common principles` `Key/value files` section level.
=> [FIX] Fix `Common principles` `Key/value files` section level

src/05-derivatives/01-introduction.md
#345  discuss splitting a pipeline into multiple derivatives with/without nesting
=> specify further the pipeline following #345

src/02-common-principles.md, src/03-modality-agnostic-files.md, src/99-appendices/01-contributors.md
Fixes issue https://github.com/bids-standard/bids-specification/issues/360
=> [FIX] Change recommended anonymization date from 1900 to 1925

src/02-common-principles.md
closes #387, please see discussion therein.
=> [FIX] improve wording on data dictionaries

src/index.md
Minor changes to specification language to improve readability on any platform, whether the RTD website RTD or the PDF (#431).
=> [FIX] Eliminate web/online-specific language

src/99-appendices/01-contributors.md
Added Alexander Jones and Kay Robbins to contributor list.
=> Added contributors from VisLab

mkdocs.yml, src/CHANGES.md
This PR marks the start of our 1 week [release process](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md#4-open-a-pull-request-against-the-master-branch). 
We are processing a minor release due to the impending addition of [Genetic Information](https://github.com/bids-standard/bids-specification/pull/395) into the Specification. 
This release also includes:
- Adds PDF rendering of the Specification
- Adds an Optional EthicsApprovals field
- Adds issue templates for GitHub
- Adds GitHub maintainer account to handle automatic work
=> REL: v1.3.0

mkdocs.yml
step 8 of the [release protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md) resetting the latest version name
=> REL: 1.3.1-dev

README.md
adding the zenodo badge for the PDF versions of the spec to the README.
=> [INFRA] add zenodo badge to README

DECISION-MAKING.md, src/99-appendices/01-contributors.md
- Fix typos in DECISION-MAKING
- Dr. Whitaker and Dr. Poldrack's names were misspelled.
- Minor capitalization and formatting changes in the file as well.
- Add myself to contributors.
- **Answering Questions** from NeuroStars.
- **Documentation and specification** from #128.
- **Plugin/utility libraries** from pybids contributions.
=> [FIX] Typos in DECISION-MAKING file

LICENSE
=> [INFRA] add copyright holder to license. 

DECISION-MAKING.md
Closes None.
- Add @tsalo as a BIDS maintainer.
=> [MISC] Add tsalo as a BIDS maintainer

src/02-common-principles.md, src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md, src/99-appendices/01-contributors.md
closes #611 
see also: https://github.com/bids-standard/bids-specification/commit/dc52b40e27e0831dcef35adaaef7a42da26c7051
=> [ENH] Add a definition for "deprecation"

src/01-introduction.md, src/04-modality-specific-files/02-magnetoencephalography.md, src/04-modality-specific-files/03-electroencephalography.md, src/04-modality-specific-files/04-intracranial-electroencephalography.md, src/04-modality-specific-files/08-genetic-descriptor.md
=> [MISC] consolidate BIDS citations in introduction

mkdocs.yml, src/99-appendices/01-contributors.md, src/CHANGES.md
closes #607 
PR initializes our [week freeze](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md) while we prepare to release this patch.
=> REL: v1.4.1

src/01-introduction.md
https://doi.org/10.1093/gigascience/giaa104
=> ENH: Update genetics-BIDS citation

DECISION-MAKING.md
=> [MISC] add remi as maintainer

src/01-introduction.md
This pull request updates the 01-introduction.md to include PET (Knudsen et al. 2020).
=> Updated 01-introduction.md to include PET

.mailmap
So that `git shortlog` could be used to establish references etc.
@josator2 @wouterpotters @agahkarakuzu @Hboni , please check if I "did you right" and again thanks for your contributions!
=> [MISC] Added full names for some contributors in .mailmap file

src/04-modality-specific-files/09-positron-emission-tomography.md
Fixing error in the URL to PET data sets @melanieganz
=> [FIX] Updated links for example PET data sets

src/02-common-principles.md
=> [MISC] add IETF standard link for json

src/02-common-principles.md
=> [ENH] clarify that entities MUST be unique

src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md
Adds new physio metadata fields into macro to generate tables.
Implements #806 into #774
=> Update physio metadata

src/02-common-principles.md
=> [FIX] correct file location of scans.tsv file in example

CONTRIBUTING.md
fixes #838 
This is not perfect but provides some guidance on how to use the metadata table macros.
=> [INFRA] Add basic documentation on how to use metadata table macros

src/06-longitudinal-and-multi-site-studies.md
=> [FIX] update physio bids name in longitudinal study page examples

src/06-longitudinal-and-multi-site-studies.md
=> [FIX] Make subheadings consistent in  06-longitudinal-and-multi-site-studies.md

DECISION-MAKING.md
@bendhouseart 
same as for the bids-website. :wink: (https://github.com/bids-standard/bids-website/pull/198)
=> [DOC] add Anthony as maintainer

src/04-modality-specific-files/04-intracranial-electroencephalography.md
Hopefully just fixing the syntax fixes the error.
Closes #931.
=> [INFRA/FIX] Use string concatenation in table macro

mkdocs.yml
Let's see if this closes #925.
=> [INFRA] expand submenus on landing page automatically

src/05-derivatives/01-introduction.md, src/05-derivatives/02-common-data-types.md, src/05-derivatives/03-imaging.md
=> [FIX] Add links from derivatives section to entity list

src/04-modality-specific-files/04-intracranial-electroencephalography.md
closes #893 
I consider this PR a bugfix, see the three first comments in #893.
=> [FIX] relax unrealistically strict requirements with ieeg channels.tsv 'name' column

DECISION-MAKING.md
Updated things on the website but not here
-  [x] add Ariel
@KirstieJane @arokem
=> [DOC] update steering group composition

src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
someone double check but I believe this sentence does not belong there
=> [FIX] typo: extra sentence in anat section

mkdocs.yml, src/99-appendices/01-contributors.md, src/CHANGES.md
Processing the release of v1.7.0
PR sets the timer on the 5-day project freeze prior to release.
=> REL: v1.7.0

CODEOWNERS
interested in schema related changes as ancp-bids heavily depends on the structure of it
=> [MISC] Update CODEOWNERS

src/02-common-principles.md
closes #1009 
the initial discussion in #1009 was triggered by a typo that is fixed in this PR.
If there is interest in using this opportunity to tweak the spec text for better understanding, please make suggestions @yarikoptic @ghisvail @effigies
=> [FIX] typo in "rawdata" example

src/schema/rules/sidecars/asl.yaml, src/schema/rules/sidecars/eeg.yaml, src/schema/rules/sidecars/fmap.yaml, src/schema/rules/sidecars/func.yaml, src/schema/rules/sidecars/ieeg.yaml, src/schema/rules/sidecars/meg.yaml, src/schema/rules/sidecars/micr.yaml, src/schema/rules/sidecars/mri.yaml, src/schema/rules/sidecars/pet.yaml
To reduce confusion between `addendum` and `level_addendum`.
=> Replace `addendum` with `description_addendum`

src/schema/rules/tabular_data/pet.yaml
cherry-pick relevant commits from blood tsv branch.
=> [SCHEMA] Define blood.tsv columns

README.md
Small change to make it look better for Github dark theme.
=> [MNT] Set light and dark mode image for logo in README

src/03-modality-agnostic-files.md
=> [MISC] make dataset_description.Authors RECOMMENDED

tools/schemacode/schemacode/validator.py
schema representation changed again, adapted logic to continue to populate list of suffixes which are directories.
=> logic update addressing literals being moved under the `value` key

tools/schemacode/schemacode/tests/data/broken_dataset_description.json, tools/schemacode/schemacode/tests/test_validator.py, tools/schemacode/schemacode/validator.py
Relatively minor change, but pretty important for usage in the wild.
=> [ENH] Catch and report invalid JSON in dataset_description

src/schema/objects/metadata.yaml
trying a fix for an issue introduced by merging #1000
will hopefully clear the way for: #1151 #1143
=> [SCHEMA] add missing display_name

tools/schemacode/bidsschematools/tests/conftest.py, tools/schemacode/bidsschematools/tests/test_validator.py
Reduces test suite duration from 38s to about 6s locally.
=> [INFRA] Reduced BIDS example download sizes

src/schema/objects/metadata.yaml
ChunkTransformationMatrixAxis had invalid schema information
=> [SCHEMA] Fixed error in BIDS metadata.yml

src/02-common-principles.md
=> [FIX] add recommendation to fully omit non-compulsory data that is n/a

src/schema/rules/common.yaml, src/schema/rules/errors.yaml
=> [SCHEMA] Common error messages for rules that have no check in schema.

src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
=> [MISC] Remove label format and inheritane principle redundancies in fMRI section

src/schema/objects/entities.yaml
=> [SCHEMA] add task definition to schema

src/schema/rules/errors.yaml, tools/mkdocs_macros_bids/macros.py, tools/schemacode/bidsschematools/render.py
Closes None.
- Address YAML formatting errors introduced in https://github.com/bids-standard/bids-specification/pull/1146.
=> [FIX] Address YAML formatting errors in schema/rules/errors.yaml

.circleci/config.yml, .github/workflows/schemacode_ci.yml, requirements.txt, tools/mkdocs_macros_bids/macros.py, tools/no-bad-latin.py, tools/schemacode/bidsschematools/__init__.py, tools/schemacode/bidsschematools/utils.py, tools/schemacode/bidsschematools/validator.py, tools/schemacode/setup.cfg
Ideally we might want to consider whether render can work without numpy/pandas altogether... but probably too big a task at this point.
@tsalo @yarikoptic
=> Metadata improvements and moved pandas and numpy to optional deps

tools/schemacode/bidsschematools/render.py
=> FIX: Filter namespaces

src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md, src/04-modality-specific-files/02-magnetoencephalography.md, src/04-modality-specific-files/03-electroencephalography.md, src/04-modality-specific-files/04-intracranial-electroencephalography.md, src/04-modality-specific-files/05-task-events.md, src/04-modality-specific-files/06-physiological-and-other-continuous-recordings.md, src/04-modality-specific-files/07-behavioral-experiments.md, src/04-modality-specific-files/09-positron-emission-tomography.md, src/04-modality-specific-files/10-microscopy.md, src/05-derivatives/02-common-data-types.md, src/05-derivatives/03-imaging.md, src/schema/rules/sidecars/asl.yaml, src/schema/rules/sidecars/derivatives/common_derivatives.yaml, src/schema/rules/sidecars/events.yaml, src/schema/rules/sidecars/ieeg.yaml, src/schema/rules/sidecars/micr.yaml, src/schema/rules/sidecars/mri.yaml, src/schema/rules/sidecars/pet.yaml, tools/mkdocs_macros_bids/macros.py, tools/mkdocs_macros_bids/main.py, tools/schemacode/bidsschematools/render.py, tools/schemacode/bidsschematools/schema.py, tools/schemacode/bidsschematools/tests/test_render.py
Starting to convert our in-text tables to references to our in-schema tables.
=> ENH: Add make_sidecar_table macro that accepts a table name

src/schema/rules/datatypes/derivatives/common_imaging_derivatives.yaml
description is valid for any derivative.
=> [SCHEMA] add description entity to imaging derivative rules

.github/workflows/schemacode_ci.yml, .github/workflows/typescript_build.yml, src/schema/README.md
=> [MNT] remove skip ci checks from CI workflow

src/01-introduction.md
Dear BIDS maintainers, 
I am glad to announce that our [article](https://www.nature.com/articles/s41597-022-01571-4#citeas) for BEP001 has been published in Scientific Data.
This PR is to add this article to the list of references. 
Thank you for your great support to make this possible.
=> [MISC] Adding qMRI BIDS article reference (BEP001)

.gitignore, src/schema/rules/sidecars/pet.yaml
- Adds random rate to`src/schema/rules/sidecars/pet.yaml`
- Updates .gitignore for this poetry user, possible others
=> [FIX] Add RandomRate to PET; Update .gitignore

.circleci/config.yml, CONTRIBUTING.md
another splinter from #1219 regarding local install and install for circleci
=> [DOC] minor change on install documentation and for circle CI

src/schema/rules/checks/hints.yaml
Reviving https://github.com/bids-standard/bids-specification/pull/1077, accidentally closed.
=> SCHEMA: Add event duration hints

.github/workflows/schemacode_ci.yml, tools/schemacode/bidsschematools/validator.py
Supersedes: https://github.com/bids-standard/bids-specification/pull/1295#event-7426140754
=> [SCHEMA] Test schema code on Windows/OSX, fix small POSIX assumption

src/schema/meta/expression_tests.yaml
=> [SCHEMA] examples of expected expressions and their results for testing

src/schema/objects/datatypes.yaml, src/schema/objects/modalities.yaml, src/schema/rules/modalities.yaml
=> [ENH] Add NIRS modality to the schema

src/schema/objects/metadata.yaml
=> FIX: Unclosed link in RepetitionTimeExcitation

src/schema/rules/checks/events.yaml, src/schema/rules/files/deriv/imaging.yaml, src/schema/rules/sidecars/derivatives/common_derivatives.yaml
Restricted events check to raw datasets.
Inverted some logic in derivatives sidecars.
Removed extension entries in deriv imaging filenames that were preventing inheritance from $ref.
=> [SCHEMA] Random fixes from trying to valdiate 

tools/schemacode/bidsschematools/tests/test_validator.py, tools/schemacode/bidsschematools/validator.py
=> FIX: Ignore hidden directories correctly in validation

src/appendices/qmri.md
=> [ENH] Add qMRI fieldmap filename templates

src/common-principles.md
added a paragraph on richness versus distinctness for filenames - relates to an [issue validating `dir-` ](https://github.com/bids-standard/bids-specification/issues/1391) and philosophy behind it as exposed by @effigies
=> richness versus distinctness

.github/workflows/schema_docs.yaml
Anthony broke this, maybe this fixes it.
=> [Bug][Misc] update workflow for schema-docs

.github/workflows/schemacode_ci.yml, tools/schemacode/bidsschematools/tests/test_validator.py, tools/schemacode/setup.cfg
2023-02-Sprint special edition.
For less extensive fixes accompanying https://github.com/bids-standard/bids-specification/pull/1398
Also addressing the open-ended Tooling goal “Review issues and comments related to Python validator (trim down technical debt)”.
=> Dropping Python 3.7, code style, typos, imports

.pre-commit-config.yaml, pdf_build_src/pandoc_script.py, tools/entities_order.py, tools/examplecode/example.py, tools/mkdocs_macros_bids/macros.py, tools/mkdocs_macros_bids/main.py
And run `pre-commit run --all` to ensure that the repository is fully compliant.
=> MNT: Run black and isort separately on bidsschematools and other tools

src/common-principles.md
Individual commits describe fixes better.
Follow up to https://github.com/bids-standard/bids-specification/pull/1392 .
closes #1423
=> [FIX] fixing some minor issues introduced recently

tools/schemacode/bidsschematools/expressions.py, tools/schemacode/bidsschematools/tests/test_expressions.py, tools/schemacode/setup.cfg
Adding a Python parser for the schema expression language
=> ENH: Add expression language parser

src/schema/rules/checks/func.yaml, src/schema/rules/checks/mri.yaml
Update checks to reflect that.
=> SCHEMA type function in expression language returns a string

src/extensions.md
If it's not too early to do so, we can change this page to link to the new site.
=> [MISC] Link to new BEP guidelines.

.pre-commit-config.yaml, tools/schemacode/bidsschematools/render/tables.py, tools/schemacode/bidsschematools/rules.py
We are surprisingly close to well-typed. Or possibly we use lots of `Any`s that make everything happy.
=> BST: Run schema code through mypy in pre-commit

tools/schemacode/bidsschematools/render/text.py
=> FIX: Link to index/label definitions in glossary

.github/labeler.yml, .github/workflows/labeler.yml
=> [INFRA] add auto labeller config and workflow

DECISION-MAKING.md, src/appendices/contributors.md
adding to bids maintainers list per meeting discussion March 24.  
cc @sappelhoff could you label as `exclude-from-changelog`? thanks
=> [MISC] adding to maintainers list

src/schema/rules/checks/asl.yaml, src/schema/rules/checks/dwi.yaml, src/schema/rules/checks/hints.yaml, src/schema/rules/checks/mri.yaml, src/schema/rules/sidecars/fmap.yaml
Working through schema validation issues
=> SCHEMA: Fix rules involving fieldmaps and NIfTI headers

.circleci/config.yml
perhaps fixes the issue found in https://github.com/bids-standard/bids-specification/pull/1475
Cc @Remi-Gau
=> fix pdfbuild symbola font download

tools/schemacode/bidsschematools/validator.py
Minor fix. Currently we add a prefix substitution in the validation function, but that's not recorded anywhere.
=> Record the actual expressions we use.

tools/schemacode/bidsschematools/tests/test_make_testdata.py, tools/schemacode/setup.cfg
Closes: https://github.com/bids-standard/bids-specification/issues/1500
=> Including bidsignore files in testdata

readthedocs.yml, tools/schemacode/.readthedocs.yaml, tools/schemacode/bidsschematools/validator.py, tools/schemacode/docs/_static/black_logo.svg, tools/schemacode/docs/_static/white_logo.svg, tools/schemacode/docs/conf.py, tools/schemacode/docs/index.rst, tools/schemacode/docs/requirements.txt
Doing some stuff I mentioned in #1499.
I also want to do full autosummary generation, but I don't want to mix that up with this.
Render: https://bidsschematools--1503.org.readthedocs.build/en/1503/
=> DOC: Prettify schemacode docs

tools/schemacode/bidsschematools/__init__.py, tools/schemacode/bidsschematools/expressions.py, tools/schemacode/bidsschematools/rules.py, tools/schemacode/bidsschematools/schema.py, tools/schemacode/bidsschematools/tests/__init__.py, tools/schemacode/bidsschematools/types/__init__.py, tools/schemacode/bidsschematools/types/namespace.py, tools/schemacode/bidsschematools/validator.py
Adding module-level docstrings for modules that are missing them. (Less worried about test modules just now.)
Also realized that we were unnecessarily calling `as_file()` for reading version files.
=> DOC: Schema tools doc improvements

src/modality-specific-files/task-events.md
=> [INFRA] Fix KDEF link

src/modality-specific-files/magnetic-resonance-imaging-data.md
=> [FIX] match subject label in folder and filename in func example

src/appendices/qmri.md, src/modality-specific-files/electroencephalography.md, src/modality-specific-files/intracranial-electroencephalography.md, src/modality-specific-files/magnetic-resonance-imaging-data.md, src/modality-specific-files/magnetoencephalography.md, src/modality-specific-files/microscopy.md, src/modality-specific-files/motion.md, src/modality-specific-files/near-infrared-spectroscopy.md, src/modality-specific-files/physiological-and-other-continuous-recordings.md, src/modality-specific-files/positron-emission-tomography.md
=> [FIX] Update links to BIDS examples

DECISION-MAKING.md
Adding myself to the maintainers list.
=> [MISC] Adding Nell to list of maintainers

src/longitudinal-and-multi-site-studies.md
=> [FIX] improve longitudinal example

tools/schemacode/.readthedocs.yaml, tools/schemacode/docs/requirements.txt
=> [DOC][FIX][MAINT]  fix schema doc build in read the docs

src/schema/rules/sidecars/meg.yaml
ieeg presumably survived a copy.
=> [SCHEMA][FIX] Use meg selectors for meg rules

src/schema/objects/entities.yaml, src/schema/rules/checks/mri.yaml, src/schema/rules/checks/nirs.yaml, src/schema/rules/sidecars/anat.yaml, src/schema/rules/sidecars/asl.yaml, src/schema/rules/sidecars/dwi.yaml, src/schema/rules/sidecars/eeg.yaml, src/schema/rules/sidecars/fmap.yaml, src/schema/rules/sidecars/func.yaml, src/schema/rules/sidecars/ieeg.yaml, src/schema/rules/sidecars/meg.yaml, src/schema/rules/sidecars/micr.yaml, src/schema/rules/sidecars/motion.yaml, src/schema/rules/sidecars/mri.yaml, src/schema/rules/sidecars/nirs.yaml, src/schema/rules/sidecars/pet.yaml, src/schema/rules/tabular_data/pet.yaml
The big one is 452a0b7, which will resolve https://github.com/bids-standard/bids-examples/issues/398. Otherwise, I was mostly clearing up redundant `modality` selectors, which led to seeing some insufficiently precise selectors.
=> [SCHEMA] Various fixes on selectors and expressions

src/schema/rules/checks/events.yaml
Fixes the following failures in bids-examples:
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ eeg_ds003645s_hed                                                                                                                 │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
STIMULUS_FILE_MISSING                      sub-002_task-FacePerception_run-3_events   schema.rules.checks.events.StimulusFileM     
.tsv                                       issing                                       
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
=> SCHEMA: Ignore n/a entries in stim_file columns when checking existence

README.md
Closes none.
Given that we got X, we may as well...
=> [MAINT] add mastodon badge

src/appendices/coordinate-systems.md, src/appendices/meg-file-formats.md, src/common-principles.md, src/derivatives/common-data-types.md, src/derivatives/introduction.md, src/modality-specific-files/magnetoencephalography.md, src/modality-specific-files/microscopy.md
We typically use `'` in the spec.
=> [MISC] change `’` -> `'`

src/schema/rules/directories.yaml
WIP. Let's talk on the files tab.
=> SCHEMA: Add schema.rules.directories to specify directory layouts

src/modality-specific-files/near-infrared-spectroscopy.md
=> [FIX] Add misssing files in filename template for NIRS

Release_Protocol.md
=> [DOC] update doc on communication platforms linked in release protocol

.pre-commit-config.yaml
Would rather not wait on CI to tell me I've got a linting error.
=> MNT: Add precommit for yamllint

src/common-principles.md
- closes #1744 
Just to get the conversation started.
=> [ENH] Add warning about deidentification when sharing sourcedata

src/modality-specific-files/magnetic-resonance-spectroscopy.md, src/schema/meta/context.yaml, src/schema/objects/metadata.yaml, src/schema/rules/checks/mrs.yaml, src/schema/rules/sidecars/func.yaml, src/schema/rules/sidecars/mrs.yaml
@markmikkelsen Here is the PR I promised in https://github.com/bids-standard/bids-specification/pull/1377#issuecomment-2123375356. A bit ahead of schedule.
@rwblair Heads up that we need to add this to the validator. We're going to need to make sure our NIfTI reader can handle NIfTI-2 and header extensions.
=> [SCHEMA] MRS schema updates

requirements.txt
This PR is merely to test the GitHub-Changelog-Generator workflow. It will be merged with a "Merge commit" method. Please ignore.
=> Trigger GitHub-Changelog-Generator

src/metaschema.json, src/schema/rules/sidecars/func.yaml, src/schema/rules/sidecars/mri.yaml
May be easiest to go commit by commit.
=> fix(schema): metaschema cleanup, schema bugs caught

src/metaschema.json, src/schema/meta/context.yaml, src/schema/rules/checks/common_derivatives.yaml, src/schema/rules/checks/nirs.yaml, src/schema/rules/checks/references.yaml
Checks need to define their own error codes. Updated the metaschema to enforce this and then fleshed them out.
@rob-luke If you wouldn't mind having a look over the NIRS checks? I'm pretty sure I got the intent correct, from re-reading the spec.
=> fix(schema): Add issue definitions for all checks

CITATION.cff
=> [MAINT] bump version citation.cff

CODEOWNERS
Remove myself from the CODEOWNERS file.
=> Remove tsalo from CODEOWNERS

Release_Protocol.md
Minor update on what to update on the BIDS website after a release.
=> [MAINT] Update Release_Protocol.md

src/schema/rules/checks/general.yaml
=> schema: add check for duplicate READMEs

src/schema/rules/checks/events.yaml, src/schema/rules/checks/mri.yaml
Addresses the following validation bugs:
* https://github.com/bids-standard/bids-validator/issues/12
* https://github.com/bids-standard/bids-validator/issues/57
* https://github.com/bids-standard/bids-validator/issues/62
=> fix(schema): Fix/add schema checks for metadata and associated files

readthedocs.yml
This PR is aimed at speeding up the build time, which currently clocks in at 2.5m. Let's see if we can't shave off at least 30s.
=> chore(rtd): Speed up doc build with uv

src/schema/README.md
=> doc(schema): Add definition field for objects.columns entries

CONTRIBUTING.md
This PR removes a contradicting sentence and fixes some typos in `CONTRIBUTING.md`
=> [FIX] Remove contradicting sentence and fix typos in `CONTRIBUTING.md`

src/metaschema.json, src/schema/rules/files/deriv/imaging.yaml, src/schema/rules/files/deriv/preprocessed_data.yaml, src/schema/rules/files/deriv/tables.yaml
=> feat(schema): Add selectors to file rules

tools/schemacode/src/bidsschematools/validator.py
I am surprised that none of the tests picked it up
=> Fix log line %interpolation in validator.py

src/common-principles.md
=> [FIX] Update links in common-principles.md

src/schema/objects/metadata.yaml
came up while reviewing... but could be wrong and we demand only BIDS datasets there?
=> [ENH] Clarify that "source datasets" do not have to be BIDS, and provide definitions for DOI and URL

src/schema/rules/checks/channels.yaml
- Add omission of microephys datatypes for overall channel file rule
=> Updates for microephys datatype
